/**
 * Fun, team-specific taglines referencing championships, iconic players, and memorable moments.
 * Used on the navbar badge instead of generic "{team} Fan".
 */

const TEAM_TAGLINES: Record<string, string[]> = {
  // ── NFL ──
  'Kansas City Chiefs': [
    'Mahomes Era', 'Run It Back', 'Kingdom Member', 'Chiefs Kingdom',
    'Three-Peat Believers', 'Arrowhead Faithful', 'Red Friday Rider',
    'Kelce Stan', 'Back to Back Champs', 'Tomahawk Nation',
    'Super Bowl Regular', 'Andy Reid Disciple', 'Patrick\'s Republic',
  ],
  'San Francisco 49ers': [
    'The Faithful', 'Bang Bang Niner Gang', 'Montana to Rice Legacy',
    'Gold Rush Member', 'Faithful to the Bay', 'NFC West Kings',
    'Levi\'s Stadium Local', 'Brock Purdy Believer', 'Niners Til I Die',
    'West Coast Offense OG', 'Harbaugh Left But We\'re Still Here',
  ],
  'Philadelphia Eagles': [
    'Philly Special Forever', 'Bird Gang', 'No One Likes Us, We Don\'t Care',
    'E-A-G-L-E-S Chant', 'Jalen Hurts Believer', 'Rocky Steps Runner',
    'Brotherly Shove Defender', 'Broad Street Bully Adjacent',
    'Fly Eagles Fly', 'Green Machine Member', 'Chase Greatness',
    'Bleeder Green', 'South Philly Native', 'Dawkins Disciple',
  ],
  'Dallas Cowboys': [
    'America\'s Team', 'How Bout Them Cowboys', 'Staubach Stan',
    'Star Power', 'AT&T Stadium Tourist', 'Jerry World Regular',
    'Emmitt Smith Era Kid', 'Troy Aikman Acolyte', 'Dak Believer',
    'Most Hated, Most Loved', 'Romo Defender', 'Dem Boyz',
    '90s Dynasty Witness', 'Star on the Helmet',
  ],
  'Green Bay Packers': [
    'Titletown Faithful', 'Lambeau Loyal', 'Frozen Tundra Tested',
    'Cheesehead Proud', 'Lambeau Leap Dreamer', 'Rodgers Era Survivor',
    'Favre Before Rodgers', 'Ice Bowl Descendant', 'Stock Owner',
    'Shareholder Meeting Regular', 'Lombardi\'s Legacy', 'Love the Quarterback',
    'Small Market Big Heart', 'Green & Gold Bleeder',
  ],
  'New England Patriots': [
    'Dynasty Witness', '28-3 Survivor', 'Do Your Job',
    'Belichick Disciple', 'Brady Era Mourner', 'Six Rings Deep',
    'Gillette Stadium Faithful', 'Gronk Party Crasher', 'Spygate Denier',
    'Tom\'s Last Dance Watcher', 'AFC East Bully', 'NFL Shield Hater',
    'Patriot Way Believer', 'Foxborough Local',
  ],
  'Buffalo Bills': [
    'Bills Mafia', 'Table Smasher', 'Circle the Wagons',
    'Shout Song Singer', 'Kelly Era Kid', 'Four Straight Super Bowl Survivor',
    'Orchard Park Tailgater', 'Josh Allen Believer', 'Highmark Faithful',
    'One Buffalo', 'Diggs Era', 'WNY Proud', 'Flurry Bowl Witness',
    'Never Quit Nation',
  ],
  'Pittsburgh Steelers': [
    'Steel Curtain Legacy', 'Terrible Towel Twirler', 'Six Rings Deep',
    'Immaculate Reception Descendant', 'Yinzer Proud', 'North Side Dweller',
    'Big Ben Era Witness', 'Franco\'s Italian Army', 'Here We Go Steelers',
    'Acrisure Faithful', 'Bradshaw Believer', 'Bus Route Regular',
    'AFC North Bully', 'Black & Gold Bleeder',
  ],
  'Denver Broncos': [
    'Mile High Saluter', 'This One\'s for Pat', 'Elway Drive Believer',
    'Altitude Advantage', 'Bowlen\'s Legacy', 'Super Bowl 50 Witness',
    'Von Miller Stan', 'Mile High Magic', 'Orange Crush Descendant',
    'Back-to-Back 97-98', 'Empower Field Faithful', 'Royal Blue Switcher',
  ],
  'Chicago Bears': [
    'Monsters of the Midway', 'Ditka Disciple', '85 Bears Forever',
    'Soldier Field Loyalist', 'Da Bears Proper', 'Halas Hall Historian',
    'Butkus Believer', 'Navy Pier Neighbor', 'Still Waiting on a QB',
    'Shufflin\' Crew Member', 'Super Bowl XX Witness', 'Windy City Warrior',
    'Payton Legacy Keeper', 'Chicago First',
  ],
  'Las Vegas Raiders': [
    'Commitment to Excellence', 'Just Win Baby', 'Raider Nation',
    'Black Hole Dweller', 'Allegiant Faithful', 'Oakland Mourner',
    'Silver & Black Bleeder', 'Davis Family Loyalist', 'Fear the Shield',
    'Road Warriors', 'Bad Boy Image Keeper', 'Madd Raider',
  ],
  'Baltimore Ravens': [
    'Nevermore', 'Defense Wins Championships', 'Flock Member',
    'Ray Lewis Disciple', 'M&T Bank Faithful', 'Ed Reed Era Kid',
    'Lamar Era Believer', 'Purple & Black Proud', 'Charm City Warrior',
    'Murder of Crows', 'John Harbaugh Truther', 'AFC North Contender',
  ],
  'Miami Dolphins': [
    'Perfect Season Purist', 'Fins Up', 'Marino Era Kid',
    'Hard Rock Faithful', 'Shula\'s Legacy', 'Aqua & Orange Proud',
    'Miami Vice Colorway Fan', '72 Dolphins Respecter', 'Tua Era',
    'South Beach Baller', 'Tank for Tua Participant', 'Flipper Faithful',
  ],
  'New York Giants': [
    'Big Blue Wrecking Crew', '18-1 Spoilers', 'Helmet Catch Witness',
    'MetLife Faithful', 'Lawrence Taylor Believer', 'Eli Forever',
    'Big Blue Faithful', 'Red Zone Rival', 'Meadowlands Survivor',
    'NFC East Fighter', 'Two-Time Super Bowl Smasher', 'Giants Pride',
  ],
  'New York Jets': [
    'Broadway Joe Believer', 'J-E-T-S', 'Next Year Is Our Year',
    'Gang Green', 'Aaron Rodgers Injury Mourner', 'MetLife Sharer',
    'Still Waiting 1969', 'Super Bowl III Witness Descendant',
    'Namath Stan', 'Darkness at the Meadowlands', 'Sanchize Defender',
  ],
  'Los Angeles Rams': [
    'Horns Up', 'Greatest Show on Turf Kid', 'Fear the Horns',
    'SoFi Faithful', 'Rams House', 'Stafford Believer',
    'McVay System Truther', 'Blue & Yellow Proud', 'Hollywood Walk of Famer',
    'Super Bowl LVI Witness', 'Cooper Kupp Stan',
  ],
  'Los Angeles Chargers': [
    'Bolt Up', 'LT Legacy', 'Powder Blue Faithful',
    'SoFi Cohabitant', 'Herbert Era', 'Charger Faithful',
    'Powder Blue Purist', 'San Diego Mourner', 'Fouts Fan',
    'Lightning Struck', 'Rivers Defender',
  ],
  'Seattle Seahawks': [
    '12th Man', 'Legion of Boom Era', 'Beast Mode Witness',
    'CenturyLink Faithful', 'Loud & Proud', 'Pete Carroll Believer',
    'Lumen Field Screamer', 'Russell Wilson Mourner', 'Blue Friday Rider',
    'Sea of Blue', 'Seahawks Since Day One', 'NFC West Rival Hater',
  ],
  'Tampa Bay Buccaneers': [
    'Fire the Cannons', 'Pewter Pirate', 'Brady\'s Last Dance',
    'Sombrero Faithful', 'Red Zone Regular', 'Licht\'s Vision',
    'Bay Area Brawler', 'Mike Evans Believer', 'Super Bowl LV Witness',
    'Playoff Brady Truther', 'Bucs Up',
  ],
  'Minnesota Vikings': [
    'Skol Chanter', 'Purple People Eater', 'Minneapolis Miracle Witness',
    'US Bank Shouter', 'No Super Bowls Still Faithful', 'Diggs Home Then Away',
    'Fran Tarkenton Descendant', 'Purple & Gold Proud', 'Skol Viking',
    'Heart Attack Hotel Member', 'NFC North Fighter',
  ],
  'Cleveland Browns': [
    'Dawg Pound Loyal', 'Factory of Sadness Survivor', 'The Land',
    'Orange Helmet Faithful', 'Bernie Kosar Stan', 'FirstEnergy Faithful',
    'Never Give Up', 'Dog Pound Member', 'Cleveland Rocks',
    'Baker Believer Gone', 'Still Here Still Proud', 'Jim Brown Legacy',
  ],
  'Cincinnati Bengals': [
    'Who Dey', 'Jungle Faithful', 'Ickey Shuffle Fan',
    'Paycor Believer', 'Burrow Era', 'Ja\'Marr Chase Stan',
    'Super Bowl LVI Runner-Up', 'Who Dey Nation', 'Tiger Stripes Proud',
    'Bengal Blitz', 'River City Roarer',
  ],
  'New Orleans Saints': [
    'Who Dat', 'Brees Believer', 'Dome Patrol',
    'Black & Gold Faithful', 'Superdome Shouter', 'Katrina Survivors\' Team',
    'Payton Era Witness', 'Sean Payton Mourner', 'Who Dat Nation',
    'Mardi Gras Football', 'Saint Faithful', 'Lombardi\'s Return 2009',
  ],
  'Arizona Cardinals': [
    'Red Sea Riser', 'Bird Gang', 'Desert Cardinal',
    'State Farm Faithful', 'Bidwill Loyalist', 'Fitzgerald Forever',
    'Warner Miracle Kid', 'Highway 17 Faithful', 'Cardinal Proud',
    'Super Bowl XLIII Runner-Up', 'Kyler Era',
  ],
  'Carolina Panthers': [
    'Keep Pounding', 'Cam Newton Era Kid', 'Bank of America Faithful',
    'Black & Blue Division Fighter', 'Julius Peppers Stan',
    'Smitty Faithful', 'NFC South Brawler', 'Roaring Faithful',
    'Hornets Territory Crossover',
  ],
  'Atlanta Falcons': [
    'Rise Up', '28-3 Survivor', 'Dirty Bird',
    'Blank\'s Vision', 'Julio Jones Stan', 'Mercedes-Benz Believer',
    'Red & Black Faithful', 'NFC South Fighter', 'ATL Faithful',
    'Deion Sanders Era Kid', 'In Brotherhood',
  ],
  'Detroit Lions': [
    'One Pride', 'Honolulu Blue Believer', 'Forward Down the Field',
    'Ford Field Faithful', 'Barry Sanders Eternal', 'Never Give Up',
    'Jared Goff Convert', 'Redemption Arc Witness', 'Stafford Mourner',
    'Dan Campbell Kneecap Biter', 'NFC North Emerging', 'Pride of the D',
  ],
  'Indianapolis Colts': [
    'Blue Crew', 'Manning Era Witness', 'Shoe Legacy',
    'Lucas Oil Faithful', 'Reggie Wayne Stan', 'Unitas Descendant',
    'Horseshoe Proud', '2006 Super Bowl Witness', 'Luck Era Mourner',
    'March to Canton', 'Irsay\'s Team',
  ],
  'Jacksonville Jaguars': [
    'Duval \'Til I Die', 'DTWD', 'Jag Life',
    'EverBank Faithful', 'Trevor Lawrence Era', 'Calais Campbell Stan',
    'DTWD Nation', 'London Regular', 'Fournette Loyal',
    'Khan\'s Vision', 'AFC South Fighter',
  ],
  'Tennessee Titans': [
    'Titan Up', 'One Yard Short', 'Music City Miracle',
    'Nissan Stadium Faithful', 'Derrick Henry Stan', 'Two-Gun Pete',
    'Remember the Titans', 'Oiler Transplant', 'AFC South Fighter',
    'Steve McNair Legacy', 'Blue & Red Proud',
  ],
  'Houston Texans': [
    'H-Town Holder', 'Texans True', 'Bulls on Parade',
    'NRG Faithful', 'JJ Watt Era', 'CJ Stroud Era',
    'Deep in the Heart', 'Blue Star State', 'Andre Johnson Legacy',
    'Deshaun Distancer', 'Clutch City Football',
  ],
  'Washington Commanders': [
    'Hail to the Burgundy & Gold', 'HTTR Legacy', 'FedEx Field Survivor',
    'The Hogs Era Kid', 'Riggins Faithful', 'RFK Nostalgic',
    'Burgundy & Gold Bleeder', 'NFC East Fighter', 'Comeback Kids',
  ],
  'Indianapolis Colts / Baltimore Ravens': ['Blue & Purple Blood'],

  // ── NBA ──
  'Chicago Bulls': [
    '6 Rings, 2 Three-Peats', 'Last Dance Witness', 'Jordan\'s Legacy',
    'Scottie Was Underpaid', 'United Center Faithful', 'Red & Black Proud',
    'Rodman Rebounder', 'Phil Jackson Zen Student', 'Chicago Bull For Life',
    'Pre-Jordan Hardiman Kid', 'Windy City Hooper', '72-10 Witness',
    'Derrick Rose Peak Witness',
  ],
  'Los Angeles Lakers': [
    'Lake Show Loyal', 'Showtime Forever', 'Mamba Mentality',
    'Purple & Gold Bleeder', '17 Rings Deep', 'Crypto.com Faithful',
    'Forum Club Legacy', 'Magic Era Witness', 'Kobe Forever',
    'Buss Family Loyalist', 'LeBron Came West', 'Hollywood Hoops',
    'Pat Riley Disciple', 'AD Believer',
  ],
  'Los Angeles Clippers': [
    'Clipper Nation', 'Lob City Legacy', 'Long Beach Faithful',
    'Waiting on That Ring', 'Intuit Dome Ready', 'Kawhi Believer',
    'Steve Ballmer Energy', 'Paul George Partner', 'Second Team in LA',
    'Blake Griffin Poster Kid',
  ],
  'Boston Celtics': [
    'Banner 18 Witness', 'Celtic Pride', 'Bleed Green',
    'TD Garden Faithful', 'Larry Legend Descendant', 'Big Three 2008 Witness',
    'Bill Russell Era Historian', 'Jaylen & Jayson Era', 'Garden Parquet Purist',
    'Shamrock Faithful', 'Banner 18 Gang', 'HC Mazzulla Truther',
    'Red Auerbach Cigar Club',
  ],
  'Golden State Warriors': [
    'Strength in Numbers', 'Splash Brother Stan', 'Dub Nation',
    'Chase Center Faithful', 'Oracle Arena Nostalgic', 'Steph Curry Believer',
    'Dynasty 2015-2022', 'Draymond Defender', 'Steve Kerr System',
    'Klay Thompson Eternal', 'We Believe 2007 Holdout', 'Blue & Gold Proud',
    'Hamptons Five Witness',
  ],
  'New York Knicks': [
    'Knicks Faithful', 'Ewing Era Kid', 'Blue & Orange Bleeder',
    'Garden Faithful', 'Jalen Brunson Believer', 'MSG Electric Witness',
    'Oak to IQ to Jalen', 'We Back', 'New York Basketball',
    'Spike Lee Front Row', 'Wait For It Nation', 'Starks Hater of Regrets',
    '73 Championship Descendant',
  ],
  'Brooklyn Nets': [
    'NetsWorld', 'Brooklyn Grit', 'BK All Day',
    'Barclays Center Faithful', 'New York\'s Other Team',
    'SuperTeam Survivor 2021', 'KD & Kyrie Era Mourner',
    'Jersey Transplant', 'Atlantic Division Fighter',
  ],
  'Philadelphia 76ers': [
    'Trust the Process', 'Sixers Faithful', 'AI Crossover Kid',
    'Wells Fargo Faithful', 'Joel Embiid Stan', 'Doc Rivers Forgiver',
    'Iverson Forever', 'Process Complete?', 'Philly Hoops Fan',
    'Moses Malone Era Descendant', 'Maxey Believer', 'Si, Se Puede',
  ],
  'Milwaukee Bucks': [
    'Fear the Deer', 'Giannis Era', 'Bucks in 6',
    'Fiserv Forum Faithful', 'Greek Freak Nation', '2021 Champions',
    'Kareem Legacy', 'Oscar Robertson Era Kid', 'Title Town Hoops',
    'Brew City Baller', 'Cream City Faithful',
  ],
  'Miami Heat': [
    'Heat Culture', 'White Hot', 'Wade County',
    'Kaseya Center Faithful', 'Pat Riley Disciple', 'Jimmy Buckets Era',
    'South Beach Superteam Witness', 'Mourning Forever', 'Three-Peat 2012-14',
    'Bam Adebayo Stan', 'Miami Sixth Man', 'Big 3 2010-14 Witness',
  ],
  'San Antonio Spurs': [
    'Pounding the Rock', 'Fundamental Basketball', 'Big 3 Era',
    'AT&T Center Faithful', 'Pop\'s System', 'Tim Duncan Forever',
    'Beautiful Basketball', 'Spur Nation', 'Fiesta Colorway Proud',
    'Manu & Tony Legacy', 'Victor Wembanyama Era', 'Five Rings Deep',
  ],
  'Dallas Mavericks': [
    'MFFL', '2011 Never Forget', 'Dirk Disciple',
    'American Airlines Faithful', 'Luka Era', 'Nowitzki Forever',
    'Doncic Magic Witness', 'Kidd As Coach Believer',
    'Jason Terry Gunner', 'Texas Hoops Fan', 'Mavs Country',
  ],
  'Denver Nuggets': [
    'Mile High Basketball', 'Jokic Stan', 'Nuggets Faithful',
    'Ball Arena Faithful', 'MPJ Believer', 'Altitude Ball',
    'Rainbow Skyline Colorway Fan', 'Championship 2023', 'Fat Lever Legacy',
    'Carmelo Era Kid', 'Joker Won The MVP', 'Blue Collar Hoops',
  ],
  'Phoenix Suns': [
    'Valley Boyz', 'Suns in 4', 'Nash Era Kid',
    'Footprint Center Faithful', 'KD & Booker Era', 'Seven Seconds or Less',
    'Devin Booker Stan', 'Orange & Purple Proud', 'The Valley',
    'Barkley Era Witness', 'Gorilla Mascot Fan', 'Desert Basketball',
  ],
  'Toronto Raptors': [
    'We The North', '2019 Champions', 'North Side',
    'Scotiabank Faithful', 'DeMar DeRozan Forever', 'Kawhi One Season Wonder',
    'OVO Section Regular', 'Toronto\'s Only Ring', 'North of the Border Hoops',
    'Jurassic Park Witness', 'Canadian Basketball Pioneer',
  ],
  'Cleveland Cavaliers': [
    'The Block. The Shot. The Stop.', 'All In', 'Wine & Gold',
    'Rocket Mortgage Faithful', 'LeBron Came Home', '3-1 Comeback Witness',
    'Garland Era', 'Kyrie Forgiver', 'Ohio Hoops Fan',
    'Wine & Gold Proud', 'Big Market Small Team Energy',
  ],
  'Oklahoma City Thunder': [
    'Thunder Up', 'Presti Masterplan', 'Paycom Center Faithful',
    'SGA Believer', 'Durant Left But We\'re Fine', 'Rebuilding? Nah',
    'Clay Bennett\'s Vision', 'Future Is Bright', 'Boomtown Ball',
  ],
  'Minnesota Timberwolves': [
    'Howl at the Moon', 'KG Era Kid', 'Target Center Faithful',
    'Anthony Edwards Era', 'Ant-Man Fan', 'Rudy Gobert Truther',
    'Winter Wolves', 'North Star Basketball', 'Trees and Wolves',
  ],
  'Sacramento Kings': [
    'Light the Beam', 'Purple Reign', 'Golden 1 Center Faithful',
    'Vlade Divac Fan', 'C-Webb Era Kid', 'BEAM TEAM',
    'Sacramento Proud', 'Domantas Sabonis Stan', 'Cowbell Nation',
  ],
  'Indiana Pacers': [
    'Gold Blooded', 'Reggie Miller Time', 'Gainbridge Faithful',
    'ABA Legacy', 'Tyrese Haliburton Era', 'Pacers Pride',
    'Indy Hoops Fan', 'Miller Time Survivor', 'Eastern Conference Fighter',
  ],
  'Portland Trail Blazers': [
    'Rip City', 'Dame Time', 'Blazer Faithful',
    'Moda Center Faithful', 'Brandon Roy Legacy', 'Drexler Disciple',
    'Scoot Henderson Era', 'Pacific Northwest Hoops', 'Jail Blazers Forgiver',
    'Red & Black Proud',
  ],
  'Memphis Grizzlies': [
    'Grit & Grind', 'Whoop That Trick', 'Grindhouse Loyal',
    'FedExForum Faithful', 'Ja Morant Era', 'Zach Randolph Forever',
    'Memphis Made', 'Blue Collar Basketball', 'Tony Allen Defensive Legend',
    'Conley Era Kid',
  ],
  'New Orleans Pelicans': [
    'Won\'t Bow Down', 'Pelicans Faithful', 'Smoothie King Faithful',
    'Zion Era', 'CJ McCollum Convert', 'New Orleans Hoops',
    'Gulf Coast Basketball', 'Bayou Ballers',
  ],
  'Atlanta Hawks': [
    'True to Atlanta', 'Highlight Factory', 'State Farm Faithful',
    'Trae Young Believer', 'Nique Legacy', 'ATL Hoops Fan',
    'Dunk Contest Royalty', 'Eastern Conference Grinder',
  ],
  'Charlotte Hornets': [
    'Buzz City', 'Bring Back the 90s', 'Spectrum Center Faithful',
    'Muggsy Bogues Fan', 'Baron Davis Era Kid', 'LaMelo Ball Era',
    'Pinstripe Proud', 'Teal & Purple Forever',
  ],
  'Detroit Pistons': [
    'Bad Boys Legacy', 'Pistons Powered', 'Goin\' to Work',
    'Little Caesars Arena Faithful', 'Isiah Thomas Descendant',
    'Ben Wallace Headband Fan', '2004 Champions', 'Motor City Hoops',
    'Dennis Rodman Before Chicago',
  ],
  'Houston Rockets': [
    'Clutch City', 'Hakeem\'s Legacy', 'Red Nation',
    'Toyota Center Faithful', 'The Dream Legacy', 'Harden Era Mourner',
    'Two-Peat 94-95', 'Mad Science Fan', 'Space City Ball',
    'Yao Ming Era Kid',
  ],
  'Orlando Magic': [
    'Pure Magic', 'Penny & Shaq Era Kid', 'Kia Center Faithful',
    'Dwight Howard Era', 'T-Mac Stan', 'Franz Wagner Era',
    'Central Florida Hoops', 'Amway Arena Nostalgic',
  ],
  'Utah Jazz': [
    'Take Note', 'Stockton to Malone', 'Delta Center Faithful',
    'Jazz Music Irony Enjoyer', 'Donovan Mitchell Mourner',
    'Lauri Markkanen Era', 'Utah Man Fan', 'SLC Faithful',
    'Mountain West Hoops',
  ],
  'Washington Wizards': [
    'DC Rising', 'Agent Zero Era', 'Capital One Faithful',
    'Wes Unseld Legacy', 'Wall & Beal Era', 'Jordan\'s Final Act Witness',
    'District Basketball', 'Mystics Crossover Fan',
  ],
  'San Antonio Spurs / New Orleans Pelicans': ['Texas to Louisiana'],

  // ── MLB ──
  'Chicago Cubs': [
    '2016 Never Gets Old', 'Wrigley Faithful', 'Curse Breakers',
    'Ernie Banks Legacy', 'Ivy Covered Purist', 'North Side Proud',
    'Fly the W', 'Rizzo Era Kid', 'Kris Bryant Convert',
    'Holy Cow Fan', 'Addison Russell Forgiver', 'Harry Caray Singer',
    'Billy Goat Curse Lifter', 'Day Game Faithful',
  ],
  'Chicago White Sox': [
    'South Side Pride', '2005 World Champs', 'Good Guys Wear Black',
    'Guaranteed Rate Faithful', 'Hawk Harrelson Stan', 'Disco Demolition Witness',
    'Black Sox Forgiver', 'Old Comiskey Nostalgic', 'Sox Fan',
    'Paul Konerko Legacy', 'Frank Thomas Era Kid',
  ],
  'New York Yankees': [
    '27 Rings Deep', 'Bronx Bombers', 'Pinstripe Proud',
    'Monument Park Historian', 'Ruth & Gehrig Legacy', 'Jeter Forever',
    'Core Four Witness', 'Aaron Judge Era', 'Yankee Stadium Faithful',
    'Evil Empire Member', 'Old Stadium Mourner', 'Mantle & Maris Fan',
    'Torre Era Kid', 'The Boss Legacy',
  ],
  'New York Mets': [
    'Ya Gotta Believe', 'Amazin\'s Faithful', 'LGM',
    'Citi Field Faithful', 'Shea Stadium Mourner', 'Tom Seaver Legacy',
    'Mike Piazza Forever', 'Let\'s Go Mets', 'Steve Cohen\'s Checkbook Fan',
    '86 World Series Witness', 'Queens Proud', 'Mr. Met Loyal',
  ],
  'Boston Red Sox': [
    'Curse Reversed', 'Red Sox Nation', 'Fenway Faithful',
    'Green Monster Toucher', 'Ortiz Forever', 'Schilling Complicater',
    'Ted Williams Era Descendant', 'Dunkin\' Baseball Fan',
    '2004 ALCS 3-0 Comeback Witness', 'Yaz Legacy', 'Pesky Pole Regular',
    'Fenway Frank Consumer',
  ],
  'Los Angeles Dodgers': [
    'Dodger Blue Bleeder', 'Think Blue', 'Boys in Blue',
    'Dodger Stadium Faithful', 'Clayton Kershaw Stan', 'Ohtani Era',
    'Jackie Robinson Legacy Keeper', 'Brooklyn Transplant Descendant',
    'World Series 2020 Witness', 'Fernando Valenzuela Fan',
    'Steve Garvey Era Kid', 'Chavez Ravine Regular',
  ],
  'San Francisco Giants': [
    'Torture Baseball', 'Even Year Magic', 'Orange October',
    'Oracle Park Faithful', 'Bonds Era Complicated Fan', 'Three Rings 2010s',
    'Willie Mays Eternal', 'McCovey Cove Swimmer', 'Buster Posey Stan',
    'The Catch Descendant', 'World Series Hat Trick',
  ],
  'St. Louis Cardinals': [
    'Devil Magic Believer', '11 Rings', 'Best Fans in Baseball',
    'Busch Stadium Faithful', 'Musial Descendant', 'Pujols Forever',
    'Yadier Molina Stan', 'Red Sea Regular', 'Whiteyball Legacy',
    'Cardinals Way Truther', 'Gibson Fastball Descendant',
  ],
  'Houston Astros': [
    'Earn History', 'H-Town Loyal', 'Shoot It',
    'Minute Maid Faithful', 'Altuve Believer', 'Springer Convert',
    '2017 Asterisk Denier', 'Juice Box Regular', 'Orbit Fan',
    'Bagwell & Biggio Era Kid', 'Sign Stealing Plead the Fifth',
  ],
  'Atlanta Braves': [
    'Chop On', 'Braves Country', 'TBS Generation',
    'Truist Park Faithful', 'Tomahawk Chopper', 'Hank Aaron Legacy',
    '2021 World Series Witness', 'Chipper Jones Forever',
    'Dale Murphy Era Kid', 'Bobby Cox Legacy', 'John Smoltz Believer',
  ],
  'Philadelphia Phillies': [
    'Dancing on My Own', 'Phanatic Faithful', 'Red October',
    'Citizens Bank Faithful', 'Utley & Howard Era', 'Schmidty Forever',
    'Chase Utley Slide Defender', 'Rhys Hoskins Bomb Fan',
    'Bryce Harper Convert', 'South Philly Baseball', 'The Vet Nostalgic',
  ],
  'Texas Rangers': [
    'Straight Up Texas', '2023 Champions', 'Globe Life Faithful',
    'Nolan Ryan Legacy', 'Yu Darvish Era Kid', 'Corey Seager Believer',
    'World Series 2023 Witness', 'Lone Star Baseball',
    'Ivan Rodriguez Legacy', 'First Title Ever',
  ],
  'Pittsburgh Pirates': [
    'Raise the Jolly Roger', 'Clemente\'s Legacy', 'Steel City Baseball',
    'PNC Park Faithful', 'Andrew McCutchen Era', 'Cutch Forever',
    'Willie Stargell Descendant', 'Bucco Nation', 'Most Beautiful Park',
    'We Are Family 1979',
  ],
  'San Diego Padres': [
    'Slam Diego', 'Friar Faithful', 'Brown Is Back',
    'Petco Park Faithful', 'Tatis Jr. Believer', 'Manny Being Manny',
    'Tony Gwynn Eternal', 'Father Time', 'San Diego Baseball',
    '1998 World Series Runner-Up',
  ],
  'Cleveland Guardians': [
    'Guardians of the Diamond', 'Cleveland Rocks',
    'Progressive Field Faithful', 'Pronk Legacy', 'Bob Lemon Era Descendant',
    'Chief Wahoo Retired', 'Jim Thome Stan', 'C-Land Proud',
  ],
  'Seattle Mariners': [
    'True to the Blue', 'Refuse to Lose', 'Ichiro Era Kid',
    'T-Mobile Park Faithful', 'The Safe Fan', 'Ken Griffey Jr. Forever',
    'Randy Johnson Slider Witness', 'Felix Hernandez Stan',
    'Still Waiting on a Ring', '116 Win Season 2001',
  ],
  'Milwaukee Brewers': [
    'Brew Crew', 'Bernie\'s Slide', 'Barrels Are Overrated',
    'American Family Field Faithful', 'Robin Yount Legacy',
    'Rollie Fingers Stache Fan', 'Small Market Survivor',
    'County Stadium Nostalgic', 'Christian Yelich MVP Witness',
  ],
  'Detroit Tigers': [
    'Old English D', 'Miggy Faithful', 'Comerica Park Faithful',
    'Al Kaline Legacy', 'Kirk Gibson Era Kid', 'Justin Verlander Mourner',
    'Motor City Baseball', 'Tiger Roar', 'Hank Greenberg Descendant',
  ],
  'Minnesota Twins': [
    'Twinkies Loyal', 'Small Market, Big Heart', 'Target Field Faithful',
    'Kirby Puckett Forever', 'Homer Hankie Waver', 'Joe Mauer Stan',
    'Dome Dog Consumer', '1987 & 1991 Series Witness',
    'Metrodome Nostalgic',
  ],
  'Baltimore Orioles': [
    'O-R-I-O-L-E-S', 'Bird Land', 'Camden Yards Pioneer',
    'Best Park In Baseball Fan', 'Brooks Robinson Descendant',
    'Cal Ripken Jr. Legacy', 'The Iron Man Fan', 'Adley Rutschman Era',
    'Orange & Black Proud',
  ],
  'Cincinnati Reds': [
    'Big Red Machine Legacy', 'Where It All Started', 'Great American Faithful',
    'Pete Rose Complicated Fan', 'Bench & Morgan Era Descendant',
    'Joey Votto Stan', 'First Professional Team Proud', 'Red Legs Loyal',
  ],
  'Kansas City Royals': [
    'Royal Blue Loyal', '2015 Never Forget', 'Forever Royal',
    'Kauffman Stadium Faithful', 'George Brett Legacy', 'Pine Tar Fan',
    'Salvador Perez Forever', 'Take the Crown', 'Small Market Heart',
  ],
  'Tampa Bay Rays': [
    'Rays Up', 'Flappy Bois', 'Small Budget Kings',
    'Tropicana Field Survivor', 'Analytics Believers', 'Wade Davis Convert',
    'Blake Snell Era', 'Last Place to World Series', 'Four-Man Rotation Innovator',
  ],
  'Arizona Diamondbacks': [
    'Dbacks Faithful', '2001 Walk-Off Witness', 'Chase Field Faithful',
    'Sedona Red', 'Randy Johnson Strikeout Witness', 'Luis Gonzalez Forever',
    'Pool In Field Fan', 'Desert Baseball',
  ],
  'Colorado Rockies': [
    'Purple Row', 'Blake Street Bombers', 'Rocktober',
    'Coors Field Faithful', 'Humidor Believer', 'Larry Walker Legacy',
    'Mile High Baseball', 'Nolan Arenado Mourner', 'Todd Helton Forever',
  ],
  'Miami Marlins': [
    'Marlins Swim', 'Loria Survivor', 'loanDepot Faithful',
    'Fire Sale Survivor', 'Jose Fernandez Memorial Fan',
    'Two Rings No Stadium', 'Young Core Believer',
  ],
  'Oakland Athletics': [
    'Green Collar Baseball', 'Moneyball Believers', 'White Elephant Faithful',
    'Rickey Henderson Legacy', 'The Bash Brothers Era', 'Oakland Forever',
    'Billy Beane System Truther', 'RingMaster Fan',
  ],
  'Washington Nationals': [
    'Nats Faithful', 'Fight Finished 2019', 'Nationals Park Faithful',
    'Soto Era Mourner', 'Bryce Harper Before Philly',
    'World Series 2019 Witness', 'Baby Shark Fan',
  ],
  'Los Angeles Angels': [
    'Halos Heaven', 'Rally Monkey Believer', 'Angel Stadium Faithful',
    'Trout Era Fan', 'Ohtani Was Here', 'Vladdy Sr. Legacy',
    'Nolan Ryan Before Texas', 'Anaheim Proud', 'Thunder Stix Collector',
  ],
  'Toronto Blue Jays': [
    'OK Blue Jays', 'North of the Border', '92-93 Back to Back',
    'Rogers Centre Faithful', 'Roberto Alomar Legacy', 'Robbie Alomar Era',
    'Vladimir Jr. Era', 'Joe Carter Walk-Off Witness',
    'Canada\'s Team', 'True North Baseball',
  ],
  'St. Louis Cardinals / Chicago Cubs': ['I-55 Rivalry Enjoyer'],

  // ── NHL ──
  'Chicago Blackhawks': [
    'One Goal Era', 'Chelsea Dagger Addict', 'Dynasty 2010s',
    'United Center Faithful', 'Bobby Hull Legacy', 'Stan Mikita Disciple',
    'Q System Witness', 'Kane & Toews Era', 'Indian Head Proud',
    'Madhouse on Madison', 'Three Cups in Six Years',
  ],
  'Boston Bruins': [
    'Spoked-B Loyal', 'Big Bad Bruins', 'Perfection Line',
    'TD Garden Faithful', 'Orr Forever', 'Bergeron Era',
    'Bear Flag Proud', 'David Krejci Stan', 'Bruins Bleed',
    'Never Miss the Garden', 'Bourque Legacy', 'Black & Gold Faithful',
  ],
  'New York Rangers': [
    'Blueshirts Faithful', 'Broadway Blueshirt', 'LGR',
    'Madison Square Garden Faithful', 'Messier Legacy',
    'Henrik Lundqvist Stan', 'Artemi Panarin Era', 'King of New York',
    'Old Garden Nostalgic', 'Classic Six Descendant',
  ],
  'New York Islanders': [
    'Yes Yes Yes', '4 Straight Cups', 'Isles Faithful',
    'UBS Arena Faithful', 'Mike Bossy Legacy', 'Denis Potvin Believer',
    'Bryan Trottier Stan', 'Nassau Coliseum Mourner', 'Long Island Hockey',
    'Snow Era Witness',
  ],
  'Detroit Red Wings': [
    'Hockeytown', 'Russian Five Era', 'Winged Wheel',
    'Little Caesars Arena Faithful', 'Stevie Y Legacy', 'Gordie Howe Eternal',
    'Yzerman Return', 'Four Cups 90s Witness', 'Nick Lidstrom Stan',
    'Red Wings For Life', 'Best Sweater in Hockey',
  ],
  'Montreal Canadiens': [
    '24 Cups Deep', 'Les Habitants', 'Bleu Blanc Rouge',
    'Bell Centre Faithful', 'Habs Forever', 'Rocket Richard Legacy',
    'Patrick Roy Era Kid', 'Ken Dryden Descendant', 'Road to 25',
    'Most Storied Franchise', 'Classic Habs',
  ],
  'Toronto Maple Leafs': [
    'Leaf Nation', 'Next Year Is Our Year', 'Blue & White Forever',
    'Scotiabank Faithful', 'Auston Matthews Era', 'Mitch Marner Stan',
    'Leafs Nation', '1967 Was Last Time', 'Maple Leaf Gardens Nostalgic',
    'Still Hopeful Somehow', 'Most Tortured Fanbase Medal',
  ],
  'Pittsburgh Penguins': [
    'Let\'s Go Pens', 'Sid the Kid Era', 'Back to Back 16-17',
    'PPG Paints Faithful', 'Lemieux & Crosby Legacy', 'Evgeni Malkin Stan',
    'Mario Lemieux Eternal', 'Three Cups 90s-2000s', 'Pen Faithful',
    'Black & Gold Hockey Proud',
  ],
  'Tampa Bay Lightning': [
    'Bolts Faithful', 'Back to Back Champs', 'Thunder Alley',
    'Amalie Arena Faithful', 'Stamkos Captain', 'Hedman Era',
    'Vasilevskiy Stan', 'Three Cups Era', 'Brayden Point Witness',
    'Bolts Lightning Strike',
  ],
  'Colorado Avalanche': [
    'Go Ass Hail Satan', 'Sakic Stan', 'Burgundy & Blue',
    'Ball Arena Faithful', 'Makar Era', 'Forsberg Legacy',
    'Quebec Transplant Descendant', 'Nathan MacKinnon Believer',
    '2022 Cup Witness', 'Cup Parade Member',
  ],
  'Vegas Golden Knights': [
    'Knights Faithful', 'Misfits 2018', 'VGK Day One',
    'T-Mobile Arena Faithful', 'Misfit Knights', '2023 Cup Witness',
    'Jack Eichel Convert', 'Desert Hockey Pioneer', 'Golden Edge',
    'Vegas Born Hockey Fan',
  ],
  'Florida Panthers': [
    'Cats Faithful', 'Sunrise Loyal', 'Rat Trick Witness',
    'Amerant Bank Faithful', 'Sasha Barkov Stan', 'Matthew Tkachuk Convert',
    'Rat Trick Inheritor', 'Two Finals Back to Back', 'Hockey in South Florida',
    '2024 Champions',
  ],
  'Carolina Hurricanes': [
    'Bunch of Jerks', 'Storm Surge', 'Take Warning',
    'PNC Arena Faithful', 'Bunch of Jerks Embrace', 'Svech Era',
    'Aho Believer', 'Whalers Transplant', 'Jeff Skinner Mourner',
    'Southern Hockey Pioneer',
  ],
  'Washington Capitals': [
    'Caps Faithful', 'Ovi Era', 'All Caps',
    'Capital One Faithful', 'Alexander the Great Fan', 'ROCK THE RED',
    '2018 Cup Witness', 'Nicklas Backstrom Underrated Opinion',
    'Ovechkin Goal Record Witness', 'DC Hockey',
  ],
  'Edmonton Oilers': [
    'Oil Country', 'McDavid Era', 'City of Champions',
    'Rogers Place Faithful', 'The Great Gretzky Legacy', 'McDavid Believer',
    'Leon Draisaitl Stan', 'Smythe Division Descendant', 'Oil Drop Proud',
    '80s Dynasty Descendant',
  ],
  'Dallas Stars': [
    'Stars Aligned', 'Victory Green', 'American Airlines Faithful',
    'Jamie Benn Captain', 'Pavelski Stan', 'Jason Robertson Era',
    'Mooterus Jersey Survivor', 'Mike Modano Legacy', 'Stars Hockey',
    'Stars & Stripes Blue',
  ],
  'St. Louis Blues': [
    'Play Gloria', '2019 January to June', 'Note Faithful',
    'Enterprise Center Faithful', 'Brett Hull Era Kid', 'Binnington Believer',
    'Patrick Berglund Standing O', 'David Backes Era', 'O\'Reilly Lift',
    'Heartbreak to History',
  ],
  'Nashville Predators': [
    'Smashville', 'It\'s All Your Fault', 'Catfish Thrower',
    'Bridgestone Faithful', 'Pekka Rinne Forever', 'Roman Josi Era',
    'Guitar Solo Fan', 'Forsberg Old Friend', 'Music City Hockey',
    'Barry Trotz Era Kid',
  ],
  'Minnesota Wild': [
    'State of Hockey', 'Wild Faithful', 'Xcel Energy Faithful',
    'Kirill Kaprizov Era', 'Minny Hockey Fan', 'Boudreau Era Survivor',
    'Marian Gaborik Mourner', 'Zach Parise Era Kid',
  ],
  'Calgary Flames': [
    'C of Red', 'Flames Faithful', 'Red Mile',
    'Scotiabank Saddledome Faithful', 'Iginla Era Kid', 'Tkachuk Sr Legacy',
    'Matthew Left But Still', 'Cow Town Hockey', 'Cheer Faithful',
  ],
  'Winnipeg Jets': [
    'True North', 'Whiteout Warrior', 'Canada Life Faithful',
    'Nikolaj Ehlers Stan', 'Connor Hellebuyck Believer', 'Pretzels Are Good',
    'Atlanta Thrashers Legacy', 'White Out Section Regular',
  ],
  'Seattle Kraken': [
    'Release the Kraken', 'Kraken Faithful', 'Climate Pledge Faithful',
    'New Team Energy', 'Matty Beniers Era', 'Day One Kraken Fan',
    'Expansion Draft Winner', 'Teal & Deep Sea Blue Proud',
  ],
  'Anaheim Ducks': [
    'Mighty Ducks Legacy', 'Let\'s Go Ducks', 'Honda Center Faithful',
    '2007 Cup Witness', 'Selanne Legacy', 'Kariya & Selanne Era Kid',
    'Wild Wing Fan', 'Getzlaf Forever', 'Disney Hockey Kid',
  ],
  'San Jose Sharks': [
    'Shark Territory', 'Chomp Chomp', 'SAP Center Faithful',
    'Joe Thornton Forever', 'Marleau Era', 'Brent Burns Beard Fan',
    'Teal Faithful', 'Silicon Valley Hockey', 'Patrick Marleau Record Witness',
  ],
  'Philadelphia Flyers': [
    'Broad Street Bullies', 'Flyers Faithful', 'Wells Fargo Faithful',
    'Bobby Clarke Forever', 'Bernie Parent Legacy', 'Orange & Black Proud',
    'Gritty Fan', 'Mark Recchi Era Kid', 'Legion of Doom Era Witness',
  ],
  'New Jersey Devils': [
    'Devils Faithful', 'Trap Game Kings', 'Prudential Center Faithful',
    'Marty Brodeur Forever', 'Scott Stevens Era', 'Three Cups 90s-2000s',
    'Nico Hischier Era', 'Jersey Hockey Fan', 'Jack Hughes Believer',
  ],
  'Ottawa Senators': [
    'Sens Army', 'Ottawa Faithful', 'Canadian Tire Centre Faithful',
    'Alfredsson Legacy', 'Spezza Era Kid', 'Brady Tkachuk Era',
    'Rebuild Enthusiast', 'Tim Hortons Coffee Fan',
  ],
  'Buffalo Sabres': [
    'Sabres Faithful', 'No Goal', 'KeyBank Center Faithful',
    'Gilbert Perreault Legacy', 'French Connection Descendant',
    'Jim Kelley Correspondent Fan', 'Tage Thompson Era',
    'Still Waiting For That Cup',
  ],
  'Columbus Blue Jackets': [
    '5th Line', 'CBJ Faithful', 'Nationwide Arena Faithful',
    'Rick Nash Era Kid', 'Boone Jenner Captain', 'Ohio Hockey Pioneer',
    'Cannon Fire Fan', 'Seth Jones Before Chicago',
  ],
  'Vancouver Canucks': [
    'Canucks Nation', 'Stick in Rink', 'Rogers Arena Faithful',
    'Elias Pettersson Era', 'Quinn Hughes Believer', 'Linden Legacy',
    '2011 Stanley Cup Finals Riot Witness', 'West Coast Hockey',
    'Flying Skate Colorway Purist',
  ],

  // ── College Football ──
  'Michigan Wolverines': [
    'Go Blue', 'Big House Believer', 'Hail to the Victors',
    'Harbaugh Era Survivor', 'Michigan Man', 'Meechigan Faithful',
    'A2 Resident', 'Ohio State Hater (Required)', 'Big Ten Bully',
    'Desmond Howard Heisman Kid', 'Winged Helmet Proud',
    '2024 National Champs Witness',
  ],
  'Ohio State Buckeyes': [
    'O-H-I-O', 'THE Ohio State', 'Buckeye Nation',
    'Horseshoe Faithful', 'Tressel Vest Wearer', 'Urban Legend',
    'Ryan Day Era', 'Michigan Hater (Required)', 'Dotting the I Witness',
    'Script Ohio Singer', 'Skull Session Regular',
  ],
  'Alabama Crimson Tide': [
    'Roll Tide', 'Saban Dynasty Witness', 'Crimson Faithful',
    'Bryant-Denny Faithful', 'Bear Bryant Descendant', 'Nick Saban Forever',
    'Seven National Titles Era', 'Elephant Stomper', 'Rammer Jammer Singer',
    'In Saban We Trust', 'Dynasty Life Member',
  ],
  'LSU Tigers': [
    'Geaux Tigers', 'Death Valley Dweller', 'Saturday Night Legacy',
    'Tiger Stadium Faithful', 'Purple & Gold Proud', 'Joe Burrow Era',
    'Ed Orgeron Accent Fan', 'Heisman Factory', 'Les Miles Grass Eater',
    'Death Valley When It Matters',
  ],
  'Tennessee Volunteers': [
    'Rocky Top', 'Vol Nation', 'Checker Neyland',
    'Neyland Stadium Faithful', 'Peyton Manning Descendant',
    'Big Orange Faithful', 'Smokey Dog Fan', 'Vol Walk Regular',
    'Tennessee Whiskey Drinker',
  ],
  'Georgia Bulldogs': [
    'Go Dawgs', 'How \'Bout Them Dawgs', 'Between the Hedges',
    'Sanford Stadium Faithful', 'Stetson Bennett Era', 'Back to Back Champs',
    'Kirby Smart Era', 'Uga Dog Fan', 'Dawg Nation',
    '2022-23 Dynasty Witness',
  ],
  'Notre Dame Fighting Irish': [
    'Play Like a Champion', 'Touchdown Jesus', 'The Golden Dome',
    'Notre Dame Stadium Faithful', 'Subway Alumni Member', 'NBC Saturday Fan',
    'Rudy Story Believer', 'Four Horsemen Descendant',
    'Knute Rockne Legacy', 'Irish Eyes Fan',
  ],
  'Penn State Nittany Lions': [
    'We Are', 'White Out Witness', 'Happy Valley Faithful',
    'Beaver Stadium Faithful', 'JoePa Legacy', 'Blue Band Fan',
    'Sean Clifford Era Kid', 'Nittany Nation', 'White Out Survivor',
  ],
  'Texas Longhorns': [
    'Hook \'Em', 'Horns Up', 'Bevo Believer',
    'Darrell K Royal Faithful', 'Vince Young Heisman Witness',
    'SEC Now Believer', 'Burnt Orange Proud', 'Texas Forever',
    'Longhorn Network Subscriber', 'Royal-Memorial Regular',
  ],
  'USC Trojans': [
    'Fight On', 'Trojan Faithful', 'Coliseum Kid',
    'Heritage Hall Believer', 'Reggie Bush Heisman Mourner',
    'Big Ten Transfer Supporter', 'Marcus Allen Legacy',
    'Cardinal & Gold Proud', 'Lincoln Riley Convert',
  ],
  'Clemson Tigers': [
    'All In', 'Death Valley (The Real One)', 'Tiger Rag',
    'Memorial Stadium Faithful', 'Dabo Swinney Believer',
    'Hill Descent Witness', 'Lawrence Era Kid', 'Paw Proud',
    'Two National Titles 2010s', 'Howard\'s Rock Toucher',
  ],
  'Oklahoma Sooners': [
    'Boomer Sooner', 'Sooner Faithful', 'SEC Now Believer',
    'Memorial Stadium Faithful', 'Baker Mayfield Heisman Kid',
    'Bedlam Survivor', 'Stoops Dynasty Witness', 'Crimson & Cream Proud',
    'Jalen Hurts Convert', 'OU Pride',
  ],
  'Florida Gators': [
    'Gator Nation', 'The Swamp Dweller', 'Chomp Chomp',
    'Ben Hill Griffin Faithful', 'Tebow Era Witness', 'Meyer Era Kid',
    'Two-Time 90s Champs Descendant', 'Blue & Orange Proud',
    'Spurrier Ball Fan',
  ],
  'Auburn Tigers': [
    'War Eagle', 'Kick Six Witness', 'Plainsmen Proud',
    'Jordan-Hare Faithful', 'Bo Jackson Era Kid', 'Iron Bowl Survivor',
    'Cam Newton Heisman Witness', 'Auburn Family',
    'Pat Dye Legacy', 'Tiger Walk Regular',
  ],
  'Oregon Ducks': [
    'Sco Ducks', 'Phil Knight\'s Army', 'Autzen Faithful',
    'Best Uniforms in CFB Opinion', 'Mariota Era Kid',
    'Justin Herbert Draft Witness', 'Nike Uniform Lab Fan',
    'Rose Bowl Regular', 'Pacific Northwest Football',
  ],
  'Wisconsin Badgers': [
    'On Wisconsin', 'Jump Around', 'Camp Randall Faithful',
    'Barry Alvarez Legacy', 'Ron Dayne Heisman Kid',
    'Bielema Era Survivor', 'Big Ten West Fighter',
    'Jump Around Tradition Keeper', 'Camp Randall Shaker',
  ],
  'Iowa Hawkeyes': [
    'Go Hawks', 'Kinnick Wave', 'Iowa City Faithful',
    'Kirk Ferentz Forever', 'Nile Kinnick Legacy',
    'Hawkeye Tradition Keeper', 'Big Ten Fighter',
    'Children\'s Hospital Wave Participant',
  ],
  'Michigan State Spartans': [
    'Go Green Go White', 'Sparty On', 'Spartan Stadium Faithful',
    'Dantonio Era Kid', 'Little Brother (Self Aware)',
    'Rose Bowl Winner', 'Midwest Proud', 'Spartan Nation',
  ],
  'UCLA Bruins': [
    'Go Bruins', '8 Clap', 'Wooden Legacy',
    'Rose Bowl Neighbor', 'Big Ten Convert', 'Chip Kelly Era Kid',
    'Westwood Proud', 'True Blue Fan', 'Drake London Stan',
  ],
  'Texas A&M Aggies': [
    '12th Man Origin Story', 'Gig \'Em', 'Aggieland Faithful',
    'Kyle Field Faithful', 'Corps of Cadets Fan', 'Junction Boys Descendant',
    'SEC Fighter', 'SEC Hype Recruit Witness', 'Reveille Fan',
  ],
  'Florida State Seminoles': [
    'Noles Nation', 'War Chant Signer', 'Doak Campbell Faithful',
    'Deion Sanders Pre-Colorado Fan', 'Bobby Bowden Legacy',
    'Three Titles Witness', 'Tomahawk Proud', 'Garnet & Gold',
  ],
  'Miami Hurricanes': [
    'The U', 'It\'s All About The U', 'Hard Rock Stadium Faithful',
    '5 National Titles Legacy', 'Turnover Chain Enjoyer',
    'Vinnie Testaverde Era Kid', 'South Beach Football',
  ],
  'Oklahoma State Cowboys': [
    'Go Pokes', 'Cowboys Ride For Free', 'Boone Pickens Faithful',
    'Gundy Mullet Stan', 'Bedlam Survivor', 'OSU Pride',
  ],
  'TCU Horned Frogs': [
    'Go Frogs', 'Purple Reign', 'Amon Carter Faithful',
    'Sonny Dykes Era', 'National Championship Runner-Up 2022',
    'Fort Worth Football', 'Gary Patterson Era Kid',
  ],
  'Boise State Broncos': [
    'Blue Turf Believer', 'We Want Bama Descendant',
    'Fiesta Bowl 2007 Witness', 'Smurf Turf Fan',
    'Group of Five Pride', 'Mountain West Champion',
  ],

  // ── MLS ──
  'Atlanta United': [
    'Unite & Conquer', 'Five Stripes', 'Mercedes-Benz Faithful',
    'Tata Martino Era Kid', 'Red & Black Proud', '2018 MLS Cup Witness',
    'Supporters Section Regular', 'La Bandeja North Member',
  ],
  'LAFC': [
    'Dale Dale Black & Gold', '3252 Faithful', 'BMO Stadium Faithful',
    'Bale & Chicharito Era', 'Gareth Bale Witness', 'Carlos Vela Forever',
    'Best Supporters Section in MLS Opinion', 'El Tráfico Hater',
  ],
  'Nashville SC': [
    'Valiente', 'GEODIS Faithful', 'Gold & Blue Proud',
    'Hany Mukhtar Era', 'MLS Expansion Witness', 'Tennessee Soccer Fan',
  ],
  'Minnesota United': [
    'Come On You Loons', 'Wonderwall', 'Allianz Field Faithful',
    'Dark Cloud Member', 'Loons Faithful', 'Minnesota Soccer Fan',
  ],
  'LA Galaxy': [
    'Galaxy Faithful', 'Dignity Health Faithful', 'MLS OG',
    'Beckham Era Kid', 'Landon Donovan Legacy', 'El Tráfico Participant',
    'Zlatan Era Witness', 'Five Cups Deep',
  ],
  'Seattle Sounders': [
    'Sounders Faithful', 'Lumen Field Faithful', 'March to the Match',
    'Two MLS Cups', 'Cascadia Pride', 'ECS Member',
    'Rave Green Proud', 'Clint Dempsey Era Kid',
  ],
  'Portland Timbers': [
    'Timbers Army', 'Providence Park Faithful', 'Rose City Till I Die',
    'Cascadia Pride', 'MLS Cup 2015 Witness', 'Diego Valeri Forever',
    'Log Chopper Fan',
  ],
  'Toronto FC': [
    'TFC Faithful', 'BMO Field Faithful', 'Red & White Proud',
    'Jozy Altidore Defender', 'Sebastian Giovinco Stan',
    '2017 Champions', 'Canadian Club Crossover Fan',
  ],
  'FC Dallas': [
    'Vamos Dallas', 'Toyota Stadium Faithful', 'Burn Legacy',
    'Oscar Pareja Era Kid', 'Texas Soccer Fan', 'Shark Fin Faithful',
  ],
  'Columbus Crew': [
    'Crew SC Faithful', 'Lower.com Field Faithful', 'Crew Forever',
    'First MLS Team Proud', 'MLS Cup 2020 Witness', 'Yellow & Black Proud',
    'Hudson Street Hooligans Member',
  ],
  'New England Revolution': [
    'Revs Faithful', 'Gillette Faithful', 'New England Soccer Fan',
    'Taylor Twellman Era Kid', 'Carles Gil Era', 'Revolution Pride',
  ],
  'New York City FC': [
    'City Faithful', 'Yankee Stadium Guest', 'Blue & White Proud',
    'David Villa Era Kid', 'MLS Cup 2021 Witness', 'NYC Football',
  ],
  'New York Red Bulls': [
    'Red Bulls Faithful', 'Supporter\'s Shield Collectors',
    'Harrison Resident', 'Red Bull Arena Faithful', 'Thierry Henry Stan',
    'Mike Petke Era Kid',
  ],
  'Inter Miami': [
    'Inter Miami Faithful', 'DRV PNK Faithful', 'Messi Era Witness',
    'Becks\' Dream Fan', 'Global Fan Club Member', 'Pink Kit Proud',
    'Drive Pink Member',
  ],
};

/**
 * Get a random tagline for a team. Falls back to "{teamName} Fan" if no taglines exist.
 */
export function getTeamTagline(teamName: string): string {
  const taglines = TEAM_TAGLINES[teamName];
  if (!taglines || taglines.length === 0) {
    return `${teamName} Fan`;
  }
  return taglines[Math.floor(Math.random() * taglines.length)];
}
