/**
 * Fun, team-specific taglines referencing championships, iconic players, and memorable moments.
 * Used on the home page badge instead of generic "{team} Fan".
 */

const TEAM_TAGLINES: Record<string, string[]> = {
  // ── NFL ──
  'Kansas City Chiefs': ['Mahomes Era', 'Run It Back', 'Kingdom Member'],
  'San Francisco 49ers': ['The Faithful', 'Bang Bang Niner Gang', 'Montana to Rice Legacy'],
  'Philadelphia Eagles': ['Philly Special Forever', 'Bird Gang', 'No One Likes Us, We Don\'t Care'],
  'Dallas Cowboys': ['America\'s Team', 'How Bout Them Cowboys', 'Staubach Stan'],
  'Green Bay Packers': ['Titletown Faithful', 'Lambeau Loyal', 'Frozen Tundra Tested'],
  'New England Patriots': ['Dynasty Witness', '28-3 Survivor', 'Do Your Job'],
  'Buffalo Bills': ['Bills Mafia', 'Table Smasher', 'Circle the Wagons'],
  'Pittsburgh Steelers': ['Steel Curtain Legacy', 'Terrible Towel Twirler', 'Six Rings Deep'],
  'Denver Broncos': ['Mile High Saluter', 'This One\'s for Pat', 'Elway Drive Believer'],
  'Chicago Bears': ['Monsters of the Midway', 'Ditka Disciple', '85 Bears Forever'],
  'Las Vegas Raiders': ['Commitment to Excellence', 'Just Win Baby', 'Raider Nation'],
  'Baltimore Ravens': ['Nevermore', 'Defense Wins Championships', 'Flock Member'],
  'Miami Dolphins': ['Perfect Season Purist', 'Fins Up', 'Marino Era Kid'],
  'New York Giants': ['Big Blue Wrecking Crew', '18-1 Spoilers', 'Helmet Catch Witness'],
  'New York Jets': ['Broadway Joe Believer', 'J-E-T-S', 'Next Year Is Our Year'],
  'Los Angeles Rams / Chargers': ['Horns Up', 'Greatest Show on Turf Kid'],
  'Los Angeles Rams': ['Horns Up', 'Greatest Show on Turf Kid', 'Fear the Horns'],
  'Los Angeles Chargers': ['Bolt Up', 'LT Legacy', 'Powder Blue Faithful'],
  'Seattle Seahawks': ['12th Man', 'Legion of Boom Era', 'Beast Mode Witness'],
  'Tampa Bay Buccaneers': ['Fire the Cannons', 'Pewter Pirate', 'Brady\'s Last Dance'],
  'Minnesota Vikings': ['Skol Chanter', 'Purple People Eater', 'Minneapolis Miracle Witness'],
  'Cleveland Browns': ['Dawg Pound Loyal', 'Factory of Sadness Survivor', 'The Land'],
  'Cincinnati Bengals': ['Who Dey', 'Jungle Faithful', 'Ickey Shuffle Fan'],
  'New Orleans Saints': ['Who Dat', 'Brees Believer', 'Dome Patrol'],
  'Arizona Cardinals': ['Red Sea Riser', 'Bird Gang', 'Desert Cardinal'],
  'Carolina Panthers': ['Keep Pounding', 'Cam Newton Era Kid'],
  'Atlanta Falcons': ['Rise Up', '28-3 Survivor', 'Dirty Bird'],
  'Detroit Lions': ['One Pride', 'Honolulu Blue Believer', 'Forward Down the Field'],
  'Indianapolis Colts': ['Blue Crew', 'Manning Era Witness', 'Shoe Legacy'],
  'Jacksonville Jaguars': ['Duval \'Til I Die', 'DTWD', 'Jag Life'],
  'Tennessee Titans': ['Titan Up', 'One Yard Short', 'Music City Miracle'],
  'Houston Texans': ['H-Town Holder', 'Texans True', 'Bulls on Parade'],
  'Washington Commanders': ['Hail to the Burgundy & Gold', 'HTTR Legacy'],

  // ── NBA ──
  'Chicago Bulls': ['6 Rings, 2 Three-Peats', 'Last Dance Witness', 'Jordan\'s Legacy'],
  'Los Angeles Lakers / Clippers': ['Lake Show Loyal', 'Showtime Forever'],
  'Los Angeles Lakers': ['Lake Show Loyal', 'Showtime Forever', 'Mamba Mentality'],
  'Los Angeles Clippers': ['Clipper Nation', 'Lob City Legacy'],
  'Boston Celtics': ['Banner 18 Witness', 'Celtic Pride', 'Bleed Green'],
  'Golden State Warriors': ['Strength in Numbers', 'Splash Brother Stan', 'Dub Nation'],
  'New York Knicks': ['Knicks Faithful', 'Ewing Era Kid', 'Blue & Orange Bleeder'],
  'Brooklyn Nets': ['NetsWorld', 'Brooklyn Grit'],
  'Philadelphia 76ers': ['Trust the Process', 'Sixers Faithful', 'AI Crossover Kid'],
  'Milwaukee Bucks': ['Fear the Deer', 'Giannis Era', 'Bucks in 6'],
  'Miami Heat': ['Heat Culture', 'White Hot', 'Wade County'],
  'San Antonio Spurs': ['Pounding the Rock', 'Fundamental Basketball', 'Big 3 Era'],
  'Dallas Mavericks': ['MFFL', '2011 Never Forget', 'Dirk Disciple'],
  'Denver Nuggets': ['Mile High Basketball', 'Jokic Stan', 'Nuggets Faithful'],
  'Phoenix Suns': ['Valley Boyz', 'Suns in 4', 'Nash Era Kid'],
  'Toronto Raptors': ['We The North', '2019 Champions', 'North Side'],
  'Cleveland Cavaliers': ['The Block. The Shot. The Stop.', 'All In', 'Wine & Gold'],
  'Oklahoma City Thunder': ['Thunder Up', 'Presti Masterplan'],
  'Minnesota Timberwolves': ['Howl at the Moon', 'KG Era Kid'],
  'Sacramento Kings': ['Light the Beam', 'Purple Reign'],
  'Indiana Pacers': ['Gold Blooded', 'Reggie Miller Time'],
  'Portland Trail Blazers': ['Rip City', 'Dame Time', 'Blazer Faithful'],
  'Memphis Grizzlies': ['Grit & Grind', 'Whoop That Trick', 'Grindhouse Loyal'],
  'New Orleans Pelicans': ['Won\'t Bow Down', 'Pelicans Faithful'],
  'Atlanta Hawks': ['True to Atlanta', 'Highlight Factory'],
  'Charlotte Hornets': ['Buzz City', 'Bring Back the 90s'],
  'Detroit Pistons': ['Bad Boys Legacy', 'Pistons Powered', 'Goin\' to Work'],
  'Houston Rockets': ['Clutch City', 'Hakeem\'s Legacy', 'Red Nation'],
  'Orlando Magic': ['Pure Magic', 'Penny & Shaq Era Kid'],
  'Utah Jazz': ['Take Note', 'Stockton to Malone'],
  'Washington Wizards': ['DC Rising', 'Agent Zero Era'],

  // ── MLB ──
  'Chicago Cubs': ['2016 Never Gets Old', 'Wrigley Faithful', 'Curse Breakers'],
  'Chicago White Sox': ['South Side Pride', '2005 World Champs', 'Good Guys Wear Black'],
  'New York Yankees': ['27 Rings Deep', 'Bronx Bombers', 'Pinstripe Proud'],
  'New York Mets': ['Ya Gotta Believe', 'Amazin\'s Faithful', 'LGM'],
  'Boston Red Sox': ['Curse Reversed', 'Red Sox Nation', 'Fenway Faithful'],
  'Los Angeles Dodgers': ['Dodger Blue Bleeder', 'Think Blue', 'Boys in Blue'],
  'San Francisco Giants': ['Torture Baseball', 'Even Year Magic', 'Orange October'],
  'St. Louis Cardinals': ['Devil Magic Believer', '11 Rings', 'Best Fans in Baseball'],
  'Houston Astros': ['Earn History', 'H-Town Loyal', 'Shoot It'],
  'Atlanta Braves': ['Chop On', 'Braves Country', 'TBS Generation'],
  'Philadelphia Phillies': ['Dancing on My Own', 'Phanatic Faithful', 'Red October'],
  'Texas Rangers': ['Straight Up Texas', '2023 Champions'],
  'Pittsburgh Pirates': ['Raise the Jolly Roger', 'Clemente\'s Legacy', 'Steel City Baseball'],
  'San Diego Padres': ['Slam Diego', 'Friar Faithful', 'Brown Is Back'],
  'Cleveland Guardians': ['Guardians of the Diamond', 'Cleveland Rocks'],
  'Seattle Mariners': ['True to the Blue', 'Refuse to Lose', 'Ichiro Era Kid'],
  'Milwaukee Brewers': ['Brew Crew', 'Bernie\'s Slide', 'Barrels Are Overrated'],
  'Detroit Tigers': ['Old English D', 'Miggy Faithful'],
  'Minnesota Twins': ['Twinkies Loyal', 'Small Market, Big Heart'],
  'Baltimore Orioles': ['O-R-I-O-L-E-S', 'Bird Land', 'Camden Yards Pioneer'],
  'Cincinnati Reds': ['Big Red Machine Legacy', 'Where It All Started'],
  'Kansas City Royals': ['Royal Blue Loyal', '2015 Never Forget', 'Forever Royal'],
  'Tampa Bay Rays': ['Rays Up', 'Flappy Bois', 'Small Budget Kings'],
  'Arizona Diamondbacks': ['Dbacks Faithful', '2001 Walk-Off Witness'],
  'Colorado Rockies': ['Purple Row', 'Blake Street Bombers', 'Rocktober'],
  'Miami Marlins': ['Marlins Swim', 'Loria Survivor'],
  'Oakland Athletics': ['Green Collar Baseball', 'Moneyball Believers'],
  'Washington Nationals': ['Nats Faithful', 'Fight Finished 2019'],
  'Los Angeles Angels': ['Halos Heaven', 'Rally Monkey Believer'],
  'Toronto Blue Jays': ['OK Blue Jays', 'North of the Border', '92-93 Back to Back'],

  // ── NHL ──
  'Chicago Blackhawks': ['One Goal Era', 'Chelsea Dagger Addict', 'Dynasty 2010s'],
  'Boston Bruins': ['Spoked-B Loyal', 'Big Bad Bruins', 'Perfection Line'],
  'New York Rangers': ['Blueshirts Faithful', 'Broadway Blueshirt', 'LGR'],
  'New York Islanders': ['Yes Yes Yes', '4 Straight Cups', 'Isles Faithful'],
  'Detroit Red Wings': ['Hockeytown', 'Russian Five Era', 'Winged Wheel'],
  'Montreal Canadiens': ['24 Cups Deep', 'Les Habitants', 'Bleu Blanc Rouge'],
  'Toronto Maple Leafs': ['Leaf Nation', 'Next Year Is Our Year', 'Blue & White Forever'],
  'Pittsburgh Penguins': ['Let\'s Go Pens', 'Sid the Kid Era', 'Back to Back 16-17'],
  'Tampa Bay Lightning': ['Bolts Faithful', 'Back to Back Champs', 'Thunder Alley'],
  'Colorado Avalanche': ['Go Ass Hail Satan', 'Sakic Stan', 'Burgundy & Blue'],
  'Vegas Golden Knights': ['Knights Faithful', 'Misfits 2018', 'VGK Day One'],
  'Florida Panthers': ['Cats Faithful', 'Sunrise Loyal', 'Rat Trick Witness'],
  'Carolina Hurricanes': ['Bunch of Jerks', 'Storm Surge', 'Take Warning'],
  'Washington Capitals': ['Caps Faithful', 'Ovi Era', 'All Caps'],
  'Edmonton Oilers': ['Oil Country', 'McDavid Era', 'City of Champions'],
  'Dallas Stars': ['Stars Aligned', 'Victory Green'],
  'St. Louis Blues': ['Play Gloria', '2019 January to June', 'Note Faithful'],
  'Nashville Predators': ['Smashville', 'It\'s All Your Fault', 'Catfish Thrower'],
  'Minnesota Wild': ['State of Hockey', 'Wild Faithful'],
  'Calgary Flames': ['C of Red', 'Flames Faithful', 'Red Mile'],
  'Winnipeg Jets': ['True North', 'Whiteout Warrior'],
  'Seattle Kraken': ['Release the Kraken', 'Kraken Faithful'],
  'Anaheim Ducks': ['Mighty Ducks Legacy', 'Let\'s Go Ducks'],
  'San Jose Sharks': ['Shark Territory', 'Chomp Chomp'],
  'Philadelphia Flyers': ['Broad Street Bullies', 'Flyers Faithful'],
  'New Jersey Devils': ['Devils Faithful', 'Trap Game Kings'],
  'Ottawa Senators': ['Sens Army', 'Ottawa Faithful'],
  'Buffalo Sabres': ['Sabres Faithful', 'No Goal'],
  'Columbus Blue Jackets': ['5th Line', 'CBJ Faithful'],
  'Vancouver Canucks': ['Canucks Nation', 'Stick in Rink'],
  'Arizona Coyotes': ['Desert Dogs', 'Yotes Faithful'],

  // ── College Football ──
  'Michigan Wolverines': ['Go Blue', 'Big House Believer', 'Hail to the Victors'],
  'Ohio State Buckeyes': ['O-H-I-O', 'THE Ohio State', 'Buckeye Nation'],
  'Alabama Crimson Tide': ['Roll Tide', 'Saban Dynasty Witness', 'Crimson Faithful'],
  'LSU Tigers': ['Geaux Tigers', 'Death Valley Dweller', 'Saturday Night Legacy'],
  'Tennessee Volunteers': ['Rocky Top', 'Vol Nation', 'Checker Neyland'],
  'Georgia Bulldogs': ['Go Dawgs', 'How \'Bout Them Dawgs', 'Between the Hedges'],
  'Notre Dame Fighting Irish': ['Play Like a Champion', 'Touchdown Jesus', 'The Golden Dome'],
  'Penn State Nittany Lions': ['We Are', 'White Out Witness', 'Happy Valley Faithful'],
  'Texas Longhorns': ['Hook \'Em', 'Horns Up', 'Bevo Believer'],
  'USC Trojans': ['Fight On', 'Trojan Faithful', 'Coliseum Kid'],
  'Clemson Tigers': ['All In', 'Death Valley (The Real One)', 'Tiger Rag'],
  'Oklahoma Sooners': ['Boomer Sooner', 'Sooner Faithful'],
  'Florida Gators': ['Gator Nation', 'The Swamp Dweller', 'Chomp Chomp'],
  'Auburn Tigers': ['War Eagle', 'Kick Six Witness'],
  'Oregon Ducks': ['Sco Ducks', 'Phil Knight\'s Army'],
  'Wisconsin Badgers': ['On Wisconsin', 'Jump Around'],
  'Iowa Hawkeyes': ['Go Hawks', 'Kinnick Wave'],
  'Michigan State Spartans': ['Go Green Go White', 'Sparty On'],
  'UCLA Bruins': ['Go Bruins', '8 Clap', 'Wooden Legacy'],

  // ── MLS ──
  'Atlanta United': ['Unite & Conquer', 'Five Stripes'],
  'LAFC': ['Dale Dale Black & Gold', '3252 Faithful'],
  'Nashville SC': ['Valiente', 'GEODIS Faithful'],
  'Minnesota United': ['Come On You Loons', 'Wonderwall'],
};

/**
 * Get a random tagline for a team. Falls back to "{teamName} Fan" if no taglines exist.
 */
export function getTeamTagline(teamName: string): string {
  const taglines = TEAM_TAGLINES[teamName];
  if (!taglines || taglines.length === 0) {
    return `${teamName} Fan`;
  }
  return taglines[Math.floor(Math.random() * taglines.length)];
}
