-- Stadium Coordinates Migration
-- Generated by geocode-stadiums.js
-- Date: 2026-01-20T04:10:38.618Z

UPDATE stadiums SET latitude = 52.9586734, longitude = 5.9361675 WHERE id = '25287b57-453e-4484-94a3-bc8896d17a40'; -- Abe Lenstra Stadion
UPDATE stadiums SET latitude = 40.4467166, longitude = -80.0157199 WHERE id = '9b46e7dd-a8fa-48af-ba45-d6257057a815'; -- Acrisure Stadium
UPDATE stadiums SET latitude = 52.6128273, longitude = 4.7420619 WHERE id = '450e9058-d1dc-453c-b594-3a1291220901'; -- AFAS Stadion Alkmaar
UPDATE stadiums SET latitude = 36.0907359, longitude = -115.1833303 WHERE id = 'baad66b0-9640-48d8-ae0f-bbafe4d25033'; -- Allegiant Stadium
UPDATE stadiums SET latitude = 44.953139, longitude = -93.1646871 WHERE id = 'c71aa56f-6b87-4768-9f28-5476abda1042'; -- Allianz Field
UPDATE stadiums SET latitude = -23.5274971, longitude = -46.6785281 WHERE id = 'ab26d6dd-99fa-4899-8f27-e4f4d72174d0'; -- Allianz Parque
UPDATE stadiums SET latitude = 43.7051477, longitude = 7.1926033 WHERE id = 'd03c368b-7665-4e8c-aa58-ef8269e3072f'; -- Allianz Riviera
UPDATE stadiums SET latitude = -33.8891572, longitude = 151.2251352 WHERE id = '02e2ca5f-2983-4fd9-9749-2859819da4d0'; -- Allianz Stadium Sydney
UPDATE stadiums SET latitude = 32.7905076, longitude = -96.8102721 WHERE id = '299d2cec-95e5-45b6-8261-9f89ec4ea4c3'; -- American Airlines Center
UPDATE stadiums SET latitude = 50.8615471, longitude = -0.0836931 WHERE id = '897adf8b-5035-45ba-ab38-9bf42197531e'; -- American Express Stadium
UPDATE stadiums SET latitude = 43.028631, longitude = -87.9731585 WHERE id = '6021dab2-cdf4-4e3a-84a5-56758fc1c41b'; -- American Family Field
UPDATE stadiums SET latitude = 53.4309164, longitude = -2.9609314 WHERE id = 'f898f39c-afe6-4f10-9e4a-b6742f2d44e9'; -- Anfield
UPDATE stadiums SET latitude = 33.8002599, longitude = -117.8817426 WHERE id = '1ff0ee84-6acb-458e-b073-4bb062c18be7'; -- Angel Stadium of Anaheim
UPDATE stadiums SET latitude = -27.1040925, longitude = -52.6069818 WHERE id = '7f69560c-b3d3-4e60-aef3-481eb10b78fc'; -- Arena Condá
UPDATE stadiums SET latitude = 39.0489357, longitude = -94.4839993 WHERE id = '117fab8a-3ed9-4147-bf95-9c48ff53c4ac'; -- Arrowhead Stadium
UPDATE stadiums SET latitude = 28.6377017, longitude = 77.2431069 WHERE id = '1101be0e-efd6-4b24-a72e-41b4bd7c586a'; -- Arun Jaitley Stadium
UPDATE stadiums SET latitude = 52.3388329, longitude = 6.6508289 WHERE id = '4da8ab2b-6330-46ca-9853-1f5ae7074184'; -- Asito Stadion
UPDATE stadiums SET latitude = 32.7478502, longitude = -97.0928337 WHERE id = '89ee9d3e-9968-41c2-adde-635a12fa46f9'; -- AT&T Stadium
UPDATE stadiums SET latitude = 55.8870084, longitude = -4.3097507 WHERE id = '9c659994-0723-4533-8620-4d3d49e4c982'; -- Balgray
UPDATE stadiums SET latitude = 39.7486838, longitude = -105.007544 WHERE id = 'd2a63a07-1b85-4888-b907-fb9d207b784e'; -- Ball Arena
UPDATE stadiums SET latitude = 35.225774, longitude = -80.8528276 WHERE id = '895d8077-4046-496c-a395-863c7619cdef'; -- Bank of America Stadium
UPDATE stadiums SET latitude = 40.6825106, longitude = -73.9752519 WHERE id = 'e8ff0815-8709-4dbd-907c-5030cec0f08b'; -- Barclays Center
UPDATE stadiums SET latitude = 26.159732, longitude = -80.3259212 WHERE id = '9fb8a47e-2c7a-431b-b084-e19f0f04ca07'; -- BB&T Center
UPDATE stadiums SET latitude = 45.4960358, longitude = -73.5692029 WHERE id = '888b2ee5-4efa-4ab9-aca5-591bab61fbb2'; -- Bell Centre
UPDATE stadiums SET latitude = 55.7830471, longitude = -4.3032201 WHERE id = '1e679189-069c-471f-bd89-3411ce53cc6a'; -- Braidholm
UPDATE stadiums SET latitude = 51.490713, longitude = -0.2889802 WHERE id = '981db268-cc3f-4870-8bcb-4dab8d3b0720'; -- Brentford Community Stadium
UPDATE stadiums SET latitude = 36.1589806, longitude = -86.7783819 WHERE id = '6845bdac-a79e-4771-8c5f-7dbe1513b589'; -- Bridgestone Arena
UPDATE stadiums SET latitude = 33.2077203, longitude = -87.550453 WHERE id = '0df09f7c-065c-4783-a23f-17c3b13812d2'; -- Bryant-Denny Stadium
UPDATE stadiums SET latitude = 29.9510489, longitude = -90.0823076 WHERE id = 'c513c83b-b1b0-4b64-8785-f7d548d19b8e'; -- Caesars Superdome
UPDATE stadiums SET latitude = 49.8925939, longitude = -97.1437389 WHERE id = 'c1f43331-5191-4dec-be47-a93c48eada5d'; -- Canada Life Centre
UPDATE stadiums SET latitude = 45.2969069, longitude = -75.9268973 WHERE id = 'd23e535d-561c-4867-9b04-cbc87813f3b0'; -- Canadian Tire Centre
UPDATE stadiums SET latitude = 38.8981883, longitude = -77.0209378 WHERE id = 'cc5927d0-1d56-4e89-a6f9-c0d29bfed0d9'; -- Capital One Arena
UPDATE stadiums SET latitude = 45.4960358, longitude = -73.5692029 WHERE id = 'e4052db2-5944-4ef2-b5e1-411aaba730bb'; -- Centre Bell
UPDATE stadiums SET latitude = 37.7679001, longitude = -122.3874223 WHERE id = '3ede2dae-d399-48e2-88d8-e2cc3ed11b9c'; -- Chase Center
UPDATE stadiums SET latitude = 33.4454856, longitude = -112.0666928 WHERE id = 'ba2704d5-20ea-4d83-a521-73fb225a431a'; -- Chase Field
UPDATE stadiums SET latitude = 39.9059221, longitude = -75.1664804 WHERE id = '0acd9e44-d8fc-483e-803d-0d11967ef6db'; -- Citizens Bank Park
UPDATE stadiums SET latitude = 47.6219014, longitude = -122.3539905 WHERE id = '03d91634-19b8-4726-b744-e4b621f08639'; -- Climate Pledge Arena
UPDATE stadiums SET latitude = 42.3392219, longitude = -83.0488632 WHERE id = 'eaf3c89c-8006-44e7-acbd-5f3d1469ef96'; -- Comerica Park
UPDATE stadiums SET latitude = 39.7560314, longitude = -104.9929286 WHERE id = 'c9510964-b205-46ff-9676-3deff8c57d6e'; -- Coors Field
UPDATE stadiums SET latitude = 51.4749218, longitude = -0.2217448 WHERE id = '3646378b-b25f-4213-a141-f936e46c1c58'; -- Craven Cottage
UPDATE stadiums SET latitude = 34.0429979, longitude = -118.2671352 WHERE id = '557b7850-f0a0-4117-86e4-7af9aa828dfa'; -- Crypto.com Arena
UPDATE stadiums SET latitude = 52.260396, longitude = 6.1727116 WHERE id = '326baf20-6e7e-4296-bdce-508fc413641c'; -- De Adelaarshorst
UPDATE stadiums SET latitude = 52.2364432, longitude = 6.8377597 WHERE id = 'b30ecfcd-f688-4b93-a3c8-eea48f724795'; -- De Grolsch Veste
UPDATE stadiums SET latitude = 50.6119044, longitude = 3.130508 WHERE id = 'dde4f7ed-001c-490d-9f7d-f7e5ba3e2aac'; -- Decathlon Arena - Stade Pierre-Mauroy
UPDATE stadiums SET latitude = 40.7683274, longitude = -111.9010551 WHERE id = '8845b60f-31b1-4e75-8fe6-c74c378502ee'; -- Delta Center
UPDATE stadiums SET latitude = 34.0736255, longitude = -118.2398452 WHERE id = '4a57076d-8582-4445-b605-3797d3e7fc54'; -- Dodger Stadium
UPDATE stadiums SET latitude = 22.5646094, longitude = 88.3423371 WHERE id = 'fc41a5e4-78b5-4bce-8d92-93874c77ac4a'; -- Eden Gardens
UPDATE stadiums SET latitude = 53.7774021, longitude = -1.5704146 WHERE id = '48e583e5-9ebd-4ff1-905f-902114b905ad'; -- Elland Road
UPDATE stadiums SET latitude = 51.5550404, longitude = -0.1083997 WHERE id = '08334d1a-7446-4b8a-a56c-fe0912d5cd50'; -- Emirates Stadium
UPDATE stadiums SET latitude = 39.743952, longitude = -105.0192228 WHERE id = '75912905-0266-4efc-9df8-83c748dba105'; -- Empower Field at Mile High
UPDATE stadiums SET latitude = 38.6268005, longitude = -90.20262 WHERE id = '2338f94c-563d-40be-bfce-011e601d02cd'; -- Enterprise Center
UPDATE stadiums SET latitude = 39.589935, longitude = 2.6301158 WHERE id = '019a37e5-3376-4240-802e-7dc87343c2dc'; -- Estadi Mallorca Son Moix
UPDATE stadiums SET latitude = 41.9612296, longitude = 2.8289964 WHERE id = 'a3d1e207-c608-4613-9c15-49e6798cd067'; -- Estadi Municipal de Montilivi
UPDATE stadiums SET latitude = -30.0654898, longitude = -51.2349178 WHERE id = '8ae14549-7f21-4c9f-a1a6-ea3290af3841'; -- Estádio Beira-Rio
UPDATE stadiums SET latitude = 32.5061234, longitude = -116.9932231 WHERE id = '7bd10b18-4287-4df8-acff-fea46f6087f1'; -- Estadio Caliente
UPDATE stadiums SET latitude = 43.3608716, longitude = -5.8703316 WHERE id = 'd106993c-3023-4f4e-be8b-cad8cfab54a8'; -- Estadio Carlos Tartiere
UPDATE stadiums SET latitude = -22.9511333, longitude = -46.5304282 WHERE id = '23f41960-a203-430b-ad82-b4ad9898b427'; -- Estadio Cicero de Souza Marques
UPDATE stadiums SET latitude = 19.3834348, longitude = -99.1782599 WHERE id = 'ae984f5a-e137-4f06-b51b-994649c12548'; -- Estadio Ciudad de los Deportes
UPDATE stadiums SET latitude = 39.4946425, longitude = -0.3638622 WHERE id = 'f96b8834-a60e-47b3-a1f1-828dee7137a1'; -- Estadio Ciudad de Valencia
UPDATE stadiums SET latitude = 41.3780317, longitude = -8.3549951 WHERE id = '0ad56fdc-ccd5-4055-893a-bda8e40ca41f'; -- Estádio Comendador Joaquim de Almeida Freitas
UPDATE stadiums SET latitude = 37.4172353, longitude = -6.0046134 WHERE id = '7563db64-4db9-40fc-819e-853b5803a185'; -- Estadio de La Cartuja
UPDATE stadiums SET latitude = 39.9442083, longitude = -0.1034046 WHERE id = 'd1ad96a0-ce17-4790-9d9f-5376f7414c7a'; -- Estadio de la Cerámica
UPDATE stadiums SET latitude = 23.277102, longitude = -106.382566 WHERE id = 'fe2c499f-658f-42a7-b31f-fa6cba248413'; -- Estadio de Mazatlán
UPDATE stadiums SET latitude = 42.8374204, longitude = -2.6908989 WHERE id = '069458bf-f259-4165-9f04-d172d7b877bc'; -- Estadio de Mendizorroza
UPDATE stadiums SET latitude = 41.3627496, longitude = -8.7401457 WHERE id = 'f05e0729-06ce-48b7-b023-28ac92c89975'; -- Estádio do Rio Ave FC
UPDATE stadiums SET latitude = 42.7966625, longitude = -1.6371311 WHERE id = 'db43757f-03ab-4f80-9267-8a3c88e2a342'; -- Estadio El Sadar
UPDATE stadiums SET latitude = 20.7047861, longitude = -103.3276735 WHERE id = '719f1103-02a8-4c4b-8c27-6b175e80681d'; -- Estadio Jalisco
UPDATE stadiums SET latitude = 40.5119994, longitude = -8.0827943 WHERE id = 'df9b3df6-4f6d-4b1a-80a0-cbf2e838fe7b'; -- Estádio João Cardoso
UPDATE stadiums SET latitude = 38.7521563, longitude = -9.2280007 WHERE id = '8a4662c5-b913-441b-8091-f14401f1aa6c'; -- Estádio José Gomes
UPDATE stadiums SET latitude = 21.1462124, longitude = -101.6480809 WHERE id = '07f9bdd0-8618-459f-ab4e-03a49daa2b41'; -- Estadio León
UPDATE stadiums SET latitude = 38.2670445, longitude = -0.6633051 WHERE id = 'c6ecc904-f3e5-4e9a-9288-626f9284f7ac'; -- Estadio Martínez Valero
UPDATE stadiums SET latitude = -19.8659115, longitude = -43.9710434 WHERE id = 'd4bb9555-2fff-47dc-8cad-f90cfa4bb66b'; -- Estádio Mineirão
UPDATE stadiums SET latitude = 41.4012527, longitude = -8.5224396 WHERE id = '5e1566b9-401e-4a19-a724-f520f35383fc'; -- Estádio Municipal 22 de Junho
UPDATE stadiums SET latitude = 19.2871061, longitude = -99.6665644 WHERE id = 'd4a7acc8-749e-4a60-82fd-b0edbe7dd9c1'; -- Estadio Nemesio Díez
UPDATE stadiums SET latitude = 31.7530863, longitude = -106.4678289 WHERE id = '7f785106-f602-4aac-8fe3-4cc454299506'; -- Estadio Olímpico Benito Juárez
UPDATE stadiums SET latitude = -22.893194, longitude = -43.2935691 WHERE id = '550e7504-0f71-4d0c-beaa-bc2074abd518'; -- Estádio Olímpico Nilton Santos
UPDATE stadiums SET latitude = 19.3316881, longitude = -99.1922864 WHERE id = '67b5b039-c175-460c-b264-28f20eb4a8d5'; -- Estadio Olímpico Universitario
UPDATE stadiums SET latitude = 37.3840876, longitude = -5.9706309 WHERE id = '4f0e823a-fd32-4e4e-b0f8-fe18b7d0f5c6'; -- Estadio Ramón Sánchez Pizjuán
UPDATE stadiums SET latitude = -22.8908007, longitude = -43.2282681 WHERE id = '5adc4ae1-433e-4bc8-8860-ccffa39619bf'; -- Estádio São Januário
UPDATE stadiums SET latitude = -23.9511157, longitude = -46.3389913 WHERE id = '2382f4fd-287d-4348-9a4b-6e2135bff572'; -- Estádio Urbano Caldeira
UPDATE stadiums SET latitude = 21.8806558, longitude = -102.2754788 WHERE id = 'f1c5bc31-867d-4cef-a88c-336eda659431'; -- Estadio Victoria
UPDATE stadiums SET latitude = 53.2062038, longitude = 6.591465 WHERE id = 'bee039de-e0e0-4116-9ff6-666e5946010d'; -- Euroborg
UPDATE stadiums SET latitude = 48.0213778, longitude = 7.829817 WHERE id = '3dc8dff8-f94e-4498-a5dc-5a13a5ab72a0'; -- Europa-Park Stadion
UPDATE stadiums SET latitude = 30.3239811, longitude = -81.6373046 WHERE id = 'c645c961-0a73-4156-a7d4-2200be4a51e7'; -- EverBank Stadium
UPDATE stadiums SET latitude = 35.1382401, longitude = -90.0506946 WHERE id = '16fb2b71-45bb-46bf-b402-49fa3a14b67a'; -- FedExForum
UPDATE stadiums SET latitude = 42.3464614, longitude = -71.0970999 WHERE id = '92dede46-9668-4ab4-8c3f-91264d169e4c'; -- Fenway Park
UPDATE stadiums SET latitude = 43.0450096, longitude = -87.9174871 WHERE id = 'f11770f3-6a45-4200-94eb-abc4550d3b1d'; -- Fiserv Forum
UPDATE stadiums SET latitude = 42.3399567, longitude = -83.0456166 WHERE id = '247eef09-0966-490c-bf81-a10cd198438e'; -- Ford Field
UPDATE stadiums SET latitude = 50.9923044, longitude = 5.8433379 WHERE id = 'f7f0b638-516b-430a-835c-2cde3eb6f58a'; -- Fortuna Sittard Stadion
UPDATE stadiums SET latitude = 29.4269205, longitude = -98.4375058 WHERE id = 'b8a8431f-b428-4d25-b479-6d3106e4fb94'; -- Frost Bank Center
UPDATE stadiums SET latitude = 39.7639331, longitude = -86.1555024 WHERE id = 'd9efe3fc-bf12-41f9-ad94-1918f8e39441'; -- Gainbridge Fieldhouse
UPDATE stadiums SET latitude = 39.0489309, longitude = -94.4839991 WHERE id = '48750830-2884-4854-bc79-9c2975fb1460'; -- GEHA Field at Arrowhead Stadium
UPDATE stadiums SET latitude = 36.130025, longitude = -86.7659442 WHERE id = '2b599f29-c205-4a56-b953-4b4d45e97593'; -- GEODIS Park
UPDATE stadiums SET latitude = 42.0908879, longitude = -71.2641731 WHERE id = '6be707e7-060c-4b33-837d-bc5c0c0cc0f8'; -- Gillette Stadium
UPDATE stadiums SET latitude = -35.2500232, longitude = 149.1026191 WHERE id = '2790b9a3-575d-431c-b4d3-a844ced5a37f'; -- GIO Stadium
UPDATE stadiums SET latitude = 32.747642, longitude = -97.0841049 WHERE id = '9caefa6b-abda-4ad4-b638-cd4c297e0488'; -- Globe Life Field
UPDATE stadiums SET latitude = 51.8224848, longitude = 5.8371565 WHERE id = 'cf5c5a31-0d69-44df-b13c-c9e017d13674'; -- Goffertstadion
UPDATE stadiums SET latitude = 38.5801405, longitude = -121.4995008 WHERE id = '98f354e0-0812-4b70-8185-1f045e51714d'; -- Golden 1 Center
UPDATE stadiums SET latitude = 44.9447659, longitude = -93.1010851 WHERE id = 'e7061bb7-f32b-4201-b93d-1f06992c80f4'; -- Grand Casino Arena
UPDATE stadiums SET latitude = 39.0972484, longitude = -84.5066233 WHERE id = '4000f67a-de33-48ee-bf4e-39ffb6305b9a'; -- Great American Ball Park
UPDATE stadiums SET latitude = 45.7653624, longitude = 4.9820543 WHERE id = 'effefbc1-323a-4407-a094-5cf54c602dd0'; -- Groupama Stadium
UPDATE stadiums SET latitude = 25.9579032, longitude = -80.2388497 WHERE id = 'c4d5684a-3304-4d56-addd-2c88fe5440f5'; -- Hard Rock Stadium
UPDATE stadiums SET latitude = -31.9457271, longitude = 115.8699183 WHERE id = 'c004a5a2-f743-4798-8b54-36a7e52bc5ad'; -- HBF Park
UPDATE stadiums SET latitude = 42.7737334, longitude = -78.7868798 WHERE id = '69a0f260-a85d-4d1d-9899-f23f6f974f4c'; -- Highmark Stadium
UPDATE stadiums SET latitude = -34.9075037, longitude = 138.5689336 WHERE id = '167641bc-e9fd-4152-95b1-d5f0665206d2'; -- Hindmarsh Stadium
UPDATE stadiums SET latitude = 33.8078316, longitude = -117.876534 WHERE id = 'd1968cd9-cf32-48bd-863d-d937fbba6a64'; -- Honda Center
UPDATE stadiums SET latitude = 41.5060559, longitude = -81.6997118 WHERE id = '9ab8ebcd-7b95-40c3-b4e4-8036b2cec9e0'; -- Huntington Bank Field
UPDATE stadiums SET latitude = 33.9442586, longitude = -118.3421719 WHERE id = '2c727d81-19ad-45c0-b369-7af354545af2'; -- Intuit Dome
UPDATE stadiums SET latitude = 52.314353, longitude = 4.9428431 WHERE id = 'fad4b5ef-2027-4658-8131-040df0ad9bff'; -- Johan Cruijff ArenA
UPDATE stadiums SET latitude = 25.7813596, longitude = -80.1879435 WHERE id = '689136c1-8f23-4f4e-beed-7fcb97ea96f9'; -- Kaseya Center
UPDATE stadiums SET latitude = 39.0515081, longitude = -94.4804598 WHERE id = '42c1ec61-6dda-444d-b214-a2bd74b2f641'; -- Kauffman Stadium
UPDATE stadiums SET latitude = 28.5392867, longitude = -81.3838892 WHERE id = '67a4c777-6165-4461-97a6-2ba35a661757'; -- Kia Center
UPDATE stadiums SET latitude = 44.5009705, longitude = -88.0619681 WHERE id = '705046ef-7df5-464d-8a1d-cc0d57d5f402'; -- Lambeau Field
UPDATE stadiums SET latitude = 35.803398, longitude = -78.7219166 WHERE id = 'f709d1f0-080f-4214-80e9-ed75ab23fe08'; -- Lenovo Center
UPDATE stadiums SET latitude = 37.4029867, longitude = -121.9696489 WHERE id = '437162d0-6132-4961-8842-05497c5ab9c6'; -- Levi's Stadium
UPDATE stadiums SET latitude = 39.9009099, longitude = -75.1674892 WHERE id = '22e7b5e7-d535-4ae7-a852-33557cbd6266'; -- Lincoln Financial Field
UPDATE stadiums SET latitude = 42.3409774, longitude = -83.0549545 WHERE id = '4a30cd54-c000-48d3-b415-481d293dc236'; -- Little Caesars Arena
UPDATE stadiums SET latitude = 25.7780733, longitude = -80.219554 WHERE id = '86dde346-eb5d-49ea-be08-899d0280bc7c'; -- LoanDepot Park
UPDATE stadiums SET latitude = 39.7590621, longitude = -86.1638376 WHERE id = '4511cbd1-e964-4c62-adc4-15a01dd8c544'; -- Lucas Oil Stadium
UPDATE stadiums SET latitude = 47.5953459, longitude = -122.3316443 WHERE id = 'fe48fb2e-602f-46b6-adf1-ceae8af315ce'; -- Lumen Field
UPDATE stadiums SET latitude = 39.2779734, longitude = -76.6226651 WHERE id = '10e64e57-470e-4f18-ba6c-fe95f7b720ae'; -- M&T Bank Stadium
UPDATE stadiums SET latitude = 52.5169311, longitude = 6.1209481 WHERE id = 'cca19365-c522-4d84-a065-c5072694663d'; -- MAC³PARK Stadion
UPDATE stadiums SET latitude = 40.7505129, longitude = -73.9935159 WHERE id = '03bd3eaf-6809-460f-8939-c56b58f925aa'; -- Madison Square Garden
UPDATE stadiums SET latitude = 55.8870992, longitude = -3.3350985 WHERE id = 'a4c44677-89bd-46ac-965b-96d27b993d0c'; -- Malleny Park
UPDATE stadiums SET latitude = 55.4321425, longitude = -2.7666692 WHERE id = 'c49e7abe-54b5-4e5d-bf79-a5706dc240d6'; -- Mansfield Park
UPDATE stadiums SET latitude = 51.3447436, longitude = -0.5465822 WHERE id = 'f7b0fce4-ac20-4750-aaaa-bf519a6dac82'; -- McLaren Technology Centre
UPDATE stadiums SET latitude = 33.7554123, longitude = -84.4008493 WHERE id = '7b36fc70-ab33-417f-8496-e7261a2f0563'; -- Mercedes-Benz Stadium
UPDATE stadiums SET latitude = 33.7554123, longitude = -84.4008493 WHERE id = '16ddc4a4-d242-4523-9961-ebe9ae3b1fdc'; -- Mercedes-Benz Stadium
UPDATE stadiums SET latitude = 40.8135071, longitude = -74.0743442 WHERE id = '2059c0d7-ac94-47da-9468-0d4d4affc583'; -- MetLife Stadium
UPDATE stadiums SET latitude = 42.2658749, longitude = -83.7486841 WHERE id = '1195238c-2385-45e9-811a-1ceb8e46ffb2'; -- Michigan Stadium
UPDATE stadiums SET latitude = 29.7572321, longitude = -95.3552344 WHERE id = 'c63d180a-2391-43a4-b6ea-929f3e95e4da'; -- Minute Maid Park
UPDATE stadiums SET latitude = 45.5315787, longitude = -122.6668337 WHERE id = 'c8baac38-311f-4025-933f-f59b8d70642a'; -- Moda Center
UPDATE stadiums SET latitude = 52.5902723, longitude = -2.1304079 WHERE id = '975df987-22da-4946-b03b-70665476a7ee'; -- Molineux Stadium
UPDATE stadiums SET latitude = 40.7229344, longitude = -73.5907243 WHERE id = 'd8857696-9def-40b8-8c91-219794003693'; -- Nassau Coliseum
UPDATE stadiums SET latitude = 38.8727332, longitude = -77.0074815 WHERE id = 'f5246d30-dcf0-46cd-9b63-39a73ef6c4f3'; -- Nationals Park
UPDATE stadiums SET latitude = 39.9691873, longitude = -83.00608 WHERE id = 'd11f47a1-8a26-423b-983a-486e2d8477c7'; -- Nationwide Arena
UPDATE stadiums SET latitude = 35.9550742, longitude = -83.9250891 WHERE id = '517805e8-7ee0-4e78-92c3-d9ee5b39947c'; -- Neyland Stadium
UPDATE stadiums SET latitude = 36.1665236, longitude = -86.7713148 WHERE id = 'aeb03650-60c8-4164-9f4f-0b296fa6c44a'; -- Nissan Stadium Nashville
UPDATE stadiums SET latitude = 38.9076875, longitude = -76.8644869 WHERE id = '3e8c3a9b-daae-4641-bdcc-7986bfd4a29a'; -- Northwest Stadium
UPDATE stadiums SET latitude = 29.6848581, longitude = -95.4108015 WHERE id = 'b0c4ddf7-e608-48c3-ad76-a4f826c69a15'; -- NRG Stadium
UPDATE stadiums SET latitude = 40.0016458, longitude = -83.0197374 WHERE id = 'd9ee0211-d5ad-4cf8-894a-f4115b33f111'; -- Ohio Stadium
UPDATE stadiums SET latitude = 53.4631095, longitude = -2.2913865 WHERE id = '57156a0a-dce8-46b6-8bea-14833a5132ff'; -- Old Trafford
UPDATE stadiums SET latitude = 37.7786059, longitude = -122.3894716 WHERE id = 'b8ca3354-ad3f-464e-9fda-f3d3c532ca0d'; -- Oracle Park
UPDATE stadiums SET latitude = 43.269835, longitude = 5.3959117 WHERE id = '252da1c6-03f1-402e-a869-810d30c84554'; -- Orange Vélodrome
UPDATE stadiums SET latitude = 39.2837383, longitude = -76.6216056 WHERE id = 'c0daa7ac-02c4-4c21-bfe3-f6b72c638308'; -- Oriole Park at Camden Yards
UPDATE stadiums SET latitude = 48.8413634, longitude = 2.2530693 WHERE id = 'ea50ec70-3759-42c1-af56-cb455ff27afd'; -- Parc des Princes
UPDATE stadiums SET latitude = 35.4633961, longitude = -97.5150815 WHERE id = '961fd132-6abc-42ae-a085-6677d9c2fb75'; -- Paycom Center
UPDATE stadiums SET latitude = 39.0954645, longitude = -84.5160488 WHERE id = '1c389733-c9e8-436e-be98-f8ed48e54759'; -- Paycor Stadium
UPDATE stadiums SET latitude = 39.7486838, longitude = -105.007544 WHERE id = '6aac8bdf-fd5f-4ef4-b310-0462e1bcf2b1'; -- Pepsi Center
UPDATE stadiums SET latitude = 32.7071882, longitude = -117.1568773 WHERE id = '12ad5b66-69fa-48d0-bc8f-86b05ea3f97b'; -- Petco Park
UPDATE stadiums SET latitude = 51.4417077, longitude = 5.4674257 WHERE id = '9a6dae7b-1f14-4ec4-a706-b8ae223c1bdc'; -- Philips Stadion
UPDATE stadiums SET latitude = 40.4469258, longitude = -80.0056063 WHERE id = 'd4d7058a-a23a-4ed6-9f22-474162589a57'; -- PNC Park
UPDATE stadiums SET latitude = 40.4395912, longitude = -79.9895408 WHERE id = '2ddd650f-bcdb-4e44-ab7f-4264daffa6da'; -- PPG Paints Arena
UPDATE stadiums SET latitude = 41.4960906, longitude = -81.6851319 WHERE id = '032e8aaa-c32f-4059-97d8-b7018405afc6'; -- Progressive Field
UPDATE stadiums SET latitude = 40.7334302, longitude = -74.1711482 WHERE id = '3b98c112-9f84-475e-b834-4a8b78fbadd6'; -- Prudential Center
UPDATE stadiums SET latitude = 55.9605569, longitude = -3.2160843 WHERE id = 'c5a50434-13cc-4b65-aae9-0fa4491e0786'; -- Raeburn Place
UPDATE stadiums SET latitude = 51.5947762, longitude = 4.7503301 WHERE id = '7ad74673-e574-43b4-a999-5d5182bdd344'; -- Rat Verlegh Stadion
UPDATE stadiums SET latitude = 27.9759793, longitude = -82.5033545 WHERE id = '52bd2b3e-551c-4875-b3a5-1ae5ab9e384d'; -- Raymond James Stadium
UPDATE stadiums SET latitude = 43.3013899, longitude = -1.9735689 WHERE id = '9ac8803d-e39b-4777-90ec-6bf32ba914e7'; -- Reale Arena
UPDATE stadiums SET latitude = 55.4920846, longitude = -2.5437971 WHERE id = '83f88153-be91-4a90-bf71-17ad86648655'; -- Riverside Park
UPDATE stadiums SET latitude = 40.436053, longitude = -3.5997153 WHERE id = '2ec35451-0a24-4ed0-92a2-faa1354ffa71'; -- Riyadh Air Metropolitano
UPDATE stadiums SET latitude = 41.4966862, longitude = -81.6885754 WHERE id = 'f7dae645-423c-4267-a7ab-102f3a1310d9'; -- Rocket Arena
UPDATE stadiums SET latitude = 49.2779085, longitude = -123.1089417 WHERE id = '3d432fa9-ac0b-4654-a998-0bcddf89d648'; -- Rogers Arena
UPDATE stadiums SET latitude = 43.7847799, longitude = -79.6264246 WHERE id = '74ee358b-7cdf-4f26-95d6-fe66f3925c74'; -- Rogers Centre
UPDATE stadiums SET latitude = 53.5467936, longitude = -113.4977946 WHERE id = 'c33dd057-08fd-45de-82d8-a4985cdb93ee'; -- Rogers Place
UPDATE stadiums SET latitude = 34.1613492, longitude = -118.1676674 WHERE id = 'afc11fe3-52e8-43ef-8ed5-d51fc1039a0f'; -- Rose Bowl
UPDATE stadiums SET latitude = 43.264204, longitude = -2.9493915 WHERE id = 'd2609d3f-95bc-4ea6-b47f-0943a430329a'; -- San Mamés Barria
UPDATE stadiums SET latitude = 37.3328604, longitude = -121.9012247 WHERE id = '49d6f5e5-bf0e-4cd7-8e36-e17aa5103d71'; -- SAP Center at San Jose
UPDATE stadiums SET latitude = 43.6434338, longitude = -79.3790777 WHERE id = '923cb617-f048-4295-a3a1-a0934251dfcb'; -- Scotiabank Arena
UPDATE stadiums SET latitude = 43.6434338, longitude = -79.3790777 WHERE id = '0b551b25-6fb9-4360-a06f-116774400e59'; -- Scotiabank Arena
UPDATE stadiums SET latitude = 51.0374124, longitude = -114.0519642 WHERE id = 'bd5e62af-0ee8-49f3-8529-53125492f287'; -- Scotiabank Saddledome
UPDATE stadiums SET latitude = 51.396882, longitude = -0.0807524 WHERE id = '36539c23-e8e5-43cf-a6fd-f6a5bef7651d'; -- Selhurst Park
UPDATE stadiums SET latitude = 29.9490393, longitude = -90.082069 WHERE id = 'd60effd9-ebae-4e6e-8153-67a0249fe5a3'; -- Smoothie King Center
UPDATE stadiums SET latitude = 33.9534074, longitude = -118.3390098 WHERE id = '740f2adc-2c31-43bd-b7a4-ae60608ef48e'; -- SoFi Stadium
UPDATE stadiums SET latitude = 41.8624515, longitude = -87.6167151 WHERE id = 'f39bf146-9456-4c09-a77b-88801b8c76ab'; -- Soldier Field
UPDATE stadiums SET latitude = 35.225098, longitude = -80.8391541 WHERE id = 'db1ba977-0229-48c1-8860-18b30b9632a8'; -- Spectrum Center
UPDATE stadiums SET latitude = 41.3808806, longitude = 2.1228182 WHERE id = '5423f51c-60f3-416f-8038-994bad58c3e8'; -- Spotify Camp Nou
UPDATE stadiums SET latitude = 54.9754693, longitude = -1.6218737 WHERE id = '966ca102-2a04-438b-936b-8c4f178f5a08'; -- St James Park
UPDATE stadiums SET latitude = 50.43281, longitude = 2.8149878 WHERE id = '1458db30-140c-4dea-adf0-cd0e80fc95c9'; -- Stade Bollaert-Delelis
UPDATE stadiums SET latitude = 47.256005, longitude = -1.5247552 WHERE id = '27ae2967-b845-412c-93df-0610879b5dae'; -- Stade de la Beaujoire - Louis Fonteneau
UPDATE stadiums SET latitude = 48.5599481, longitude = 7.7551221 WHERE id = 'a07fece0-812e-4501-be92-3b3100919596'; -- Stade de la Meinau
UPDATE stadiums SET latitude = 47.7488686, longitude = -3.3693032 WHERE id = 'b2a05e24-b592-4ffb-82c2-4d6548cb1629'; -- Stade du Moustoir
UPDATE stadiums SET latitude = 48.4030423, longitude = -4.4613605 WHERE id = 'c18e16a1-5223-4a6b-b1ac-f5e0e395468a'; -- Stade Francis-Le Blé
UPDATE stadiums SET latitude = 48.8432938, longitude = 2.252952 WHERE id = '22f3ea88-40cc-447a-9a72-f39db1e42907'; -- Stade Jean-Bouin
UPDATE stadiums SET latitude = 43.7275713, longitude = 7.4154577 WHERE id = '691b0c50-e616-4393-8a36-72d2b8d24bc4'; -- Stade Louis II
UPDATE stadiums SET latitude = 49.4987513, longitude = 0.1694637 WHERE id = 'df3e6b56-65aa-4c80-a885-2b60787185b7'; -- Stade Océane
UPDATE stadiums SET latitude = 47.4605516, longitude = -0.5306948 WHERE id = 'f2dacbb6-13a1-4bed-afdf-3ea3e63f99f1'; -- Stade Raymond Kopa
UPDATE stadiums SET latitude = 49.109636, longitude = 6.1596049 WHERE id = '57d240b1-d652-4a84-8042-ccaaea494e17'; -- Stade Saint-Symphorien
UPDATE stadiums SET latitude = 44.492317, longitude = 11.3108007 WHERE id = '60973a92-04c0-4ab6-baf8-3488a36d6cf4'; -- Stadio Renato Dall'Ara
UPDATE stadiums SET latitude = 51.8955122, longitude = 4.5254683 WHERE id = '5bd6e0a2-1648-4536-95b8-7bb4a36397e6'; -- Stadion Feyenoord
UPDATE stadiums SET latitude = 52.078356, longitude = 5.1458709 WHERE id = '9ed637fc-4f6c-486c-bb4a-872e0a8001d6'; -- Stadion Galgenwaard
UPDATE stadiums SET latitude = 43.5832262, longitude = 1.4340638 WHERE id = '3ae3c5e1-b6cc-4ea9-bd92-7363188c2db5'; -- Stadium de Toulouse
UPDATE stadiums SET latitude = 51.4816869, longitude = -0.1910336 WHERE id = '38fd5a05-5881-4014-a0fe-5e00f0606dd2'; -- Stamford Bridge
UPDATE stadiums SET latitude = 33.7573698, longitude = -84.3963848 WHERE id = '5ec0a27b-bb97-447f-9e83-041f9e36d315'; -- State Farm Arena
UPDATE stadiums SET latitude = 55.9390153, longitude = -3.0651243 WHERE id = '4eb6ad49-5105-4a60-a458-5ac5f7a6656c'; -- Stoneyhill
UPDATE stadiums SET latitude = -27.4648603, longitude = 153.0096055 WHERE id = 'df83a5e7-9f98-4be1-9a5f-dd59a80709c3'; -- Suncorp Stadium
UPDATE stadiums SET latitude = 38.5803717, longitude = -121.5134097 WHERE id = '37857863-a804-4ca6-a76f-c517956a8a83'; -- Sutter Health Park
UPDATE stadiums SET latitude = 36.102678, longitude = -115.1782239 WHERE id = 'f028b8eb-fe4e-4ff9-85b1-15368aa4c71d'; -- T-Mobile Arena
UPDATE stadiums SET latitude = 47.5913974, longitude = -122.332507 WHERE id = '44fec61c-ddc6-4c06-81b2-4a48ba06bd35'; -- T-Mobile Park
UPDATE stadiums SET latitude = 44.9795917, longitude = -93.2759828 WHERE id = 'a3d5c750-1d93-49d4-b16d-13ccdfc87ead'; -- Target Center
UPDATE stadiums SET latitude = 44.9816845, longitude = -93.2778643 WHERE id = '2212125a-2f8a-497f-92d2-05540f5e9763'; -- Target Field
UPDATE stadiums SET latitude = 42.3662986, longitude = -71.0621622 WHERE id = 'f5d9124c-b548-468c-9dc5-b1a1faa3553c'; -- TD Garden
UPDATE stadiums SET latitude = 30.4119772, longitude = -91.1838303 WHERE id = 'c0570763-e8d0-4bf4-be63-e98b4a61d08c'; -- Tiger Stadium
UPDATE stadiums SET latitude = 29.7507473, longitude = -95.3622315 WHERE id = '40a83fb7-ccfe-4580-aeed-98758b42095d'; -- Toyota Center
UPDATE stadiums SET latitude = 33.890738, longitude = -84.4676163 WHERE id = 'f45412dc-6fac-495f-b774-0e52e851635a'; -- Truist Park
UPDATE stadiums SET latitude = 53.7893606, longitude = -2.2298547 WHERE id = 'e010a4fb-9a7c-40b8-873b-534a6341b567'; -- Turf Moor
UPDATE stadiums SET latitude = 44.9751097, longitude = -93.2593387 WHERE id = '511b0476-86de-4c96-ac5a-8dce91c763d0'; -- U.S. Bank Stadium
UPDATE stadiums SET latitude = 41.8806831, longitude = -87.6741851 WHERE id = '9503f173-1e5f-4dce-9f85-caebc4f4bf05'; -- United Center
UPDATE stadiums SET latitude = 52.5091264, longitude = -1.8850354 WHERE id = '8efe9fa4-9680-49f0-bcd1-6545cff8139d'; -- Villa Park
UPDATE stadiums SET latitude = 18.9385497, longitude = 72.8257408 WHERE id = 'a0baeaa5-dd81-47cb-9dc6-4be84eb9138f'; -- Wankhede Stadium
UPDATE stadiums SET latitude = 39.951184, longitude = -75.1657179 WHERE id = 'b36edc9e-988d-4a30-bd5f-912a56d1f2b1'; -- Wells Fargo Center
UPDATE stadiums SET latitude = 41.9481846, longitude = -87.655559 WHERE id = '892ba614-0f00-4f77-937a-ad2b69859c29'; -- Wrigley Field
UPDATE stadiums SET latitude = 39.9011004, longitude = -75.1720165 WHERE id = '1950cdba-b8aa-48d0-8657-a7e23fbf4bdc'; -- Xfinity Mobile Arena
UPDATE stadiums SET latitude = 40.8295828, longitude = -73.9265212 WHERE id = '2f120726-42ca-41c0-a08a-c3c6f0660576'; -- Yankee Stadium
